import 'package:rulemind/rulemind.dart';

class StudioFixtures {
  static Map<String, dynamic> demoContent() => <String, dynamic>{
        'appName': 'RuleMind Experience Studio',
        'tagline': 'Decisioning journeys, orchestration, callbacks, and explainability in one mobile studio.',
        'version': '2026.04.01',
        'sections': <Map<String, dynamic>>[
          <String, dynamic>{'id': 'home_dashboard', 'title': 'Home', 'icon': 'home'},
          <String, dynamic>{'id': 'travel_guard', 'title': 'Travel', 'icon': 'flight'},
          <String, dynamic>{'id': 'instant_personal_loan', 'title': 'Loan', 'icon': 'account_balance'},
          <String, dynamic>{'id': 'sme_underwriting', 'title': 'SME', 'icon': 'business'},
          <String, dynamic>{'id': 'scenario_hub', 'title': 'Scenarios', 'icon': 'science'},
          <String, dynamic>{'id': 'logs_explainability', 'title': 'Logs', 'icon': 'terminal'},
          <String, dynamic>{'id': 'admin_console', 'title': 'Admin', 'icon': 'settings'},
        ],
        'journeys': <Map<String, dynamic>>[
          _travelJourney(),
          _loanJourney(),
          _smeJourney(),
        ],
        'adminTools': <Map<String, dynamic>>[
          <String, dynamic>{'id': 'threshold_controls', 'title': 'Rule Thresholds', 'description': 'Adjust sensitive limit parameters and preview decision impact.'},
          <String, dynamic>{'id': 'workflow_paths', 'title': 'Workflow Paths', 'description': 'Inspect routing branches, review-gate conditions, and fallbacks.'},
          <String, dynamic>{'id': 'callback_simulator', 'title': 'Callback Simulator', 'description': 'Trigger mock external events and queued callback flows.'},
          <String, dynamic>{'id': 'scenario_controls', 'title': 'Scenario Controls', 'description': 'Inject deterministic personas and edge-case payloads.'},
          <String, dynamic>{'id': 'decision_preview', 'title': 'Decision Preview', 'description': 'Run dry-run previews before changes are promoted.'},
          <String, dynamic>{'id': 'test_harness', 'title': 'Audit & Test Harness', 'description': 'Inspect traces, action logs, and explainability surfaces.'},
        ],
        'adminEntities': <Map<String, dynamic>>[
          _entity(
            'connectors',
            'Connectors',
            '/api/v1/connectors',
            '/api/v1/connectors/{id}',
            createPath: '/api/v1/connectors',
            updatePath: '/api/v1/connectors/{id}',
            supportsCreate: true,
            supportsDelete: true,
            fields: <Map<String, dynamic>>[
              _text('name', 'Name', required: true),
              _text('icon', 'Icon'),
              _text('color', 'Color'),
              _text('description', 'Description'),
              _jsonField('schema_paths', 'Schema Paths'),
              _jsonField('sample_payload', 'Sample Payload'),
              _boolField('is_active', 'Active'),
              _jsonField('config', 'Configuration'),
            ],
          ),
          _entity(
            'variables',
            'Variables',
            '/api/v1/variables',
            '/api/v1/variables/{id}',
            createPath: '/api/v1/variables',
            updatePath: '/api/v1/variables/{id}',
            testPath: '/api/v1/variables/{id}/test',
            supportsCreate: true,
            supportsDelete: true,
            supportsPromote: true,
            fields: <Map<String, dynamic>>[
              _text('name', 'Name', required: true),
              _text('category', 'Category', required: true),
              _text('source_id', 'Source ID', required: true),
              _choice('status', 'Status', <String>['dev', 'uat', 'prod'], required: true),
              _text('description', 'Description'),
              _codeField('code', 'Code', required: true),
            ],
          ),
          _entity(
            'rules',
            'Rules',
            '/api/v1/rules',
            '/api/v1/rules/{id}',
            createPath: '/api/v1/rules',
            updatePath: '/api/v1/rules/{id}',
            testPath: '/api/v1/rules/{id}/test',
            supportsCreate: true,
            supportsDelete: true,
            supportsPromote: true,
            fields: <Map<String, dynamic>>[
              _text('name', 'Name', required: true),
              _choice('ruleFormat', 'Rule Format', <String>['v1', 'v2'], required: true),
              _choice('status', 'Status', <String>['dev', 'uat', 'prod'], required: true),
              _jsonField('nodes', 'Nodes'),
              _jsonField('tree', 'Tree'),
            ],
          ),
          _entity(
            'scorecards',
            'Scorecards',
            '/api/v1/scorecards',
            '/api/v1/scorecards/{id}',
            createPath: '/api/v1/scorecards',
            updatePath: '/api/v1/scorecards/{id}',
            testPath: '/api/v1/scorecards/{id}/test',
            supportsCreate: true,
            supportsDelete: true,
            supportsPromote: true,
            fields: <Map<String, dynamic>>[
              _text('name', 'Name', required: true),
              _number('base_score', 'Base Score', required: true),
              _number('max_score', 'Max Score', required: true),
              _choice('status', 'Status', <String>['dev', 'uat', 'prod'], required: true),
              _jsonField('bins', 'Bins'),
            ],
          ),
          _entity(
            'policies',
            'Policies',
            '/api/v1/policies',
            '/api/v1/policies/{id}',
            createPath: '/api/v1/policies',
            updatePath: '/api/v1/policies/{id}',
            testPath: '/api/v1/policies/{id}/execute',
            supportsCreate: true,
            supportsDelete: true,
            supportsPromote: true,
            fields: <Map<String, dynamic>>[
              _text('name', 'Name', required: true),
              _choice('status', 'Status', <String>['dev', 'uat', 'prod'], required: true),
              _text('defaultOutcome', 'Default Outcome'),
              _jsonField('steps', 'Steps'),
            ],
          ),
          _entity(
            'experiments',
            'Experiments',
            '/api/v1/experiments',
            '/api/v1/experiments/{id}',
            createPath: '/api/v1/experiments',
            updatePath: '/api/v1/experiments/{id}',
            supportsCreate: true,
            supportsDelete: true,
            fields: <Map<String, dynamic>>[
              _text('name', 'Name', required: true),
              _text('description', 'Description'),
              _text('target_policy_id', 'Target Policy ID'),
              _choice('status', 'Status', <String>['draft', 'running', 'paused', 'stopped'], required: true),
              _jsonField('variants', 'Variants'),
            ],
          ),
          _entity(
            'webhooks',
            'Webhooks',
            '/api/v1/webhooks',
            '/api/v1/webhooks/{id}',
            createPath: '/api/v1/webhooks',
            updatePath: '/api/v1/webhooks/{id}',
            supportsCreate: true,
            supportsDelete: true,
            fields: <Map<String, dynamic>>[
              _text('policy_id', 'Policy ID', required: true),
              _boolField('is_active', 'Active'),
              _text('secret', 'Secret'),
              _jsonField('payload_mapping', 'Payload Mapping'),
            ],
          ),
          _entity(
            'schedules',
            'Schedules',
            '/api/v1/schedules',
            '/api/v1/schedules/{id}',
            createPath: '/api/v1/schedules',
            updatePath: '/api/v1/schedules/{id}',
            supportsCreate: true,
            supportsDelete: true,
            fields: <Map<String, dynamic>>[
              _text('policy_id', 'Policy ID', required: true),
              _text('cron_expression', 'Cron Expression', required: true),
              _boolField('is_active', 'Active'),
              _jsonField('payload_source', 'Payload Source'),
              _jsonField('config', 'Configuration'),
            ],
          ),
          _entity(
            'settings',
            'Settings',
            '/api/v1/settings',
            '/api/v1/settings',
            updatePath: '/api/v1/settings',
            fields: <Map<String, dynamic>>[
              _text('api_base_url', 'API Base URL'),
              _jsonField('auth_config', 'Auth Configuration'),
              _jsonField('engine_config', 'Engine Configuration'),
              _jsonField('source_defaults', 'Source Defaults'),
              _number('audit_retention_days', 'Audit Retention Days'),
              _choice('theme_mode', 'Theme Mode', <String>['light', 'dark']),
            ],
          ),
        ],
        'logMetrics': <Map<String, dynamic>>[
          <String, dynamic>{'label': 'Total flows executed', 'value': '128,492', 'trend': '+12% vs last week'},
          <String, dynamic>{'label': 'Active rule groups', 'value': '84', 'trend': 'All systems active'},
          <String, dynamic>{'label': 'Callback success', 'value': '99.9%', 'trend': '2 failures today'},
          <String, dynamic>{'label': 'Decision avg time', 'value': '42ms', 'trend': 'Optimal performance'},
        ],
        'scenarios': <Map<String, dynamic>>[
          ..._travelScenarios(),
          ..._loanScenarios(),
          ..._smeScenarios(),
        ],
      };

  static Bundle demoBundle() => Bundle.fromJson(<String, dynamic>{
        'bundleVersion': 7,
        'bundleId': 'rulemind-mobile-studio',
        'tenantId': 'demo-tenant',
        'compiledAt': '2026-04-01T00:00:00Z',
        'expiresAt': '2030-12-31T23:59:59Z',
        'checksum': 'sha256:rulemind-mobile-studio',
        'serverOnlyVariables': const <String>[],
        'variables': <Map<String, dynamic>>[
          _variable('travel_passport_months_valid', 'travel', 'Passport Validity', 'passport_months_valid'),
          _variable('travel_visa_ready', 'travel', 'Visa Ready', 'visa_ready'),
          _variable('travel_destination_risk', 'travel', 'Destination Risk', 'destination_risk'),
          _variable('travel_primary_age', 'travel', 'Primary Age', 'primary_traveller_age'),
          _variable('travel_medical_flag_value', 'travel', 'Medical Flag', 'medical_flag_value'),
          _variable('travel_trip_cost_inr', 'travel', 'Trip Cost', 'trip_cost_inr'),
          _variable('travel_support_matrix_ready', 'travel', 'Support Matrix Ready', 'support_matrix_ready'),
          _variable('loan_bureau_score', 'loan', 'Bureau Score', 'bureau_score'),
          _variable('loan_avg_balance_inr', 'loan', 'Average Balance', 'avg_balance_inr'),
          _variable('loan_dti_ratio', 'loan', 'DTI Ratio', 'dti_ratio'),
          _variable('loan_pan_verified_flag', 'loan', 'PAN Verified', 'pan_verified_flag'),
          _variable('loan_geo_consistency_flag', 'loan', 'Geo Consistency', 'geo_consistency_flag'),
          _variable('loan_liveness_score', 'loan', 'Liveness Score', 'liveness_score'),
          _variable('sme_gst_compliance_score', 'sme', 'GST Compliance', 'gst_compliance_score'),
          _variable('sme_census_quality_score', 'sme', 'Census Quality', 'census_quality_score'),
          _variable('sme_loss_ratio_pct', 'sme', 'Loss Ratio', 'loss_ratio_pct'),
          _variable('sme_growth_rate_pct', 'sme', 'Growth Rate', 'growth_rate_pct'),
          _variable('sme_sanctions_flag', 'sme', 'Sanctions Flag', 'sanctions_flag'),
          _variable('sme_ubo_docs_ready_flag', 'sme', 'UBO Ready', 'ubo_docs_ready_flag'),
          _variable('sme_claims_disclosed_flag', 'sme', 'Claims Disclosed', 'claims_disclosed_flag'),
        ],
        'rules': <Map<String, dynamic>>[
          _rule('rule_travel_passport_gate', 'Travel Passport Gate', 'approve', 'reject', <Map<String, dynamic>>[_condition('travel_passport_months_valid', '>=', 6)]),
          _rule('rule_travel_destination_gate', 'Travel Destination Gate', 'pass', 'review', <Map<String, dynamic>>[
            _condition('travel_destination_risk', '<=', 2),
            _condition('travel_support_matrix_ready', '>=', 1),
          ]),
          _rule('rule_travel_profile_gate', 'Travel Profile Gate', 'pass', 'review', <Map<String, dynamic>>[
            _condition('travel_visa_ready', '>=', 1),
            _condition('travel_medical_flag_value', '==', 0),
            _condition('travel_primary_age', '<=', 70),
          ]),
          _rule('rule_loan_bureau_gate', 'Loan Bureau Gate', 'approve', 'review', <Map<String, dynamic>>[_condition('loan_bureau_score', '>=', 700)]),
          _rule('rule_loan_kyc_gate', 'Loan KYC Gate', 'pass', 'reject', <Map<String, dynamic>>[
            _condition('loan_pan_verified_flag', '>=', 1),
            _condition('loan_liveness_score', '>=', 90),
          ]),
          _rule('rule_loan_geo_gate', 'Loan Geo Gate', 'pass', 'review', <Map<String, dynamic>>[_condition('loan_geo_consistency_flag', '==', 0)]),
          _rule('rule_loan_affordability_gate', 'Loan Affordability Gate', 'pass', 'reject', <Map<String, dynamic>>[_condition('loan_dti_ratio', '<=', 0.45)]),
          _rule('rule_sme_compliance_gate', 'SME Compliance Gate', 'approve', 'review', <Map<String, dynamic>>[
            _condition('sme_sanctions_flag', '==', 0),
            _condition('sme_ubo_docs_ready_flag', '>=', 1),
          ]),
          _rule('rule_sme_census_gate', 'SME Census Gate', 'pass', 'review', <Map<String, dynamic>>[_condition('sme_census_quality_score', '>=', 85)]),
          _rule('rule_sme_claims_gate', 'SME Claims Gate', 'pass', 'review', <Map<String, dynamic>>[
            _condition('sme_claims_disclosed_flag', '>=', 1),
            _condition('sme_loss_ratio_pct', '<=', 35),
          ]),
          _rule('rule_sme_growth_gate', 'SME Growth Gate', 'pass', 'review', <Map<String, dynamic>>[_condition('sme_growth_rate_pct', '<=', 50)]),
        ],
        'scorecards': <Map<String, dynamic>>[
          _scorecard('sc_travel_fit', 'Travel Fit Score', 500, <Map<String, dynamic>>[
            _factor('travel_destination_risk', <Map<String, dynamic>>[_range(0, 1, 70), _range(2, 2, 20), _range(3, 9, -60)]),
            _factor('travel_trip_cost_inr', <Map<String, dynamic>>[_range(0, 99999, 20), _range(100000, 199999, 50), _range(200000, 999999999, 30)]),
            _factor('travel_primary_age', <Map<String, dynamic>>[_range(18, 60, 40), _range(61, 74, -10), _range(75, 120, -60)]),
          ]),
          _scorecard('sc_loan_risk', 'Loan Risk Score', 500, <Map<String, dynamic>>[
            _factor('loan_bureau_score', <Map<String, dynamic>>[_range(0, 649, -120), _range(650, 699, -20), _range(700, 749, 40), _range(750, 900, 90)]),
            _factor('loan_avg_balance_inr', <Map<String, dynamic>>[_range(0, 24999, -40), _range(25000, 74999, 25), _range(75000, 999999999, 60)]),
            _factor('loan_dti_ratio', <Map<String, dynamic>>[_range(0, 0.25, 60), _range(0.251, 0.45, 15), _range(0.451, 1.0, -80)]),
          ]),
          _scorecard('sc_sme_risk', 'SME Risk Score', 520, <Map<String, dynamic>>[
            _factor('sme_gst_compliance_score', <Map<String, dynamic>>[_range(0, 79, -80), _range(80, 89, 10), _range(90, 100, 60)]),
            _factor('sme_census_quality_score', <Map<String, dynamic>>[_range(0, 79, -60), _range(80, 89, 10), _range(90, 100, 45)]),
            _factor('sme_loss_ratio_pct', <Map<String, dynamic>>[_range(0, 20, 50), _range(20.1, 35, 10), _range(35.1, 100, -70)]),
          ]),
        ],
        'policies': <Map<String, dynamic>>[
          <String, dynamic>{
            'id': 'policy_travel_guard',
            'name': 'Travel Guard',
            'defaultOutcome': 'review',
            'steps': <Map<String, dynamic>>[
              <String, dynamic>{'id': 'travel_connector', 'type': 'connector', 'refId': 'travel', 'label': 'Travel Profile'},
              <String, dynamic>{
                'id': 'travel_destination_callback',
                'type': 'action',
                'label': 'Destination Risk Lookup',
                'config': <String, dynamic>{'url': 'rulemind://simulate/travel-callback', 'method': 'POST', 'bodyTemplate': <String, dynamic>{'destination_country': '{{ payload.travel.destination_country }}'}, 'onFailure': 'continue'}
              },
              <String, dynamic>{'id': 'travel_passport_rule', 'type': 'rule', 'refId': 'rule_travel_passport_gate', 'label': 'Passport Validity'},
              <String, dynamic>{'id': 'travel_fit_score', 'type': 'scorecard', 'refId': 'sc_travel_fit', 'label': 'Travel Fit Score'},
              <String, dynamic>{'id': 'travel_destination_rule', 'type': 'rule', 'refId': 'rule_travel_destination_gate', 'label': 'Destination Gate'},
              <String, dynamic>{'id': 'travel_profile_rule', 'type': 'rule', 'refId': 'rule_travel_profile_gate', 'label': 'Traveler Profile'},
              <String, dynamic>{'id': 'travel_review_gate', 'type': 'review_gate', 'label': 'Manual Travel Review', 'config': <String, dynamic>{'assignTo': 'travel_specialist_queue', 'requiredFields': <String>['medical_clearance_note'], 'condition': "outcome == 'review'"}},
              <String, dynamic>{'id': 'travel_outcome', 'type': 'outcome', 'refId': 'approve', 'label': 'Eligibility Confirmed', 'config': <String, dynamic>{'condition': "outcome != 'reject' and outcome != 'review'"}},
            ],
          },
          <String, dynamic>{
            'id': 'policy_instant_personal_loan',
            'name': 'Instant Personal Loan Underwriting',
            'defaultOutcome': 'review',
            'steps': <Map<String, dynamic>>[
              <String, dynamic>{'id': 'loan_connector', 'type': 'connector', 'refId': 'loan', 'label': 'Loan Application'},
              <String, dynamic>{'id': 'loan_bureau_rule', 'type': 'rule', 'refId': 'rule_loan_bureau_gate', 'label': 'Bureau Threshold'},
              <String, dynamic>{'id': 'loan_risk_score', 'type': 'scorecard', 'refId': 'sc_loan_risk', 'label': 'Credit Risk Score'},
              <String, dynamic>{'id': 'loan_bureau_callback', 'type': 'action', 'label': 'Credit Bureau Callback', 'config': <String, dynamic>{'url': 'rulemind://simulate/loan-callback', 'method': 'POST', 'bodyTemplate': <String, dynamic>{'bureau_score': '{{ variables.loan_bureau_score }}'}, 'onFailure': 'continue'}},
              <String, dynamic>{'id': 'loan_kyc_rule', 'type': 'rule', 'refId': 'rule_loan_kyc_gate', 'label': 'KYC Gate'},
              <String, dynamic>{'id': 'loan_geo_rule', 'type': 'rule', 'refId': 'rule_loan_geo_gate', 'label': 'Geo Consistency'},
              <String, dynamic>{'id': 'loan_affordability_rule', 'type': 'rule', 'refId': 'rule_loan_affordability_gate', 'label': 'Affordability'},
              <String, dynamic>{'id': 'loan_review_gate', 'type': 'review_gate', 'label': 'Senior Underwriter Review', 'config': <String, dynamic>{'assignTo': 'underwriting_queue', 'requiredFields': <String>['approved_amount_inr'], 'condition': "outcome == 'review'"}},
              <String, dynamic>{'id': 'loan_outcome', 'type': 'outcome', 'refId': 'approve', 'label': 'Approved with Pricing', 'config': <String, dynamic>{'condition': "outcome != 'reject' and outcome != 'review'"}},
            ],
          },
          <String, dynamic>{
            'id': 'policy_sme_underwriting',
            'name': 'SME Underwriting',
            'defaultOutcome': 'review',
            'steps': <Map<String, dynamic>>[
              <String, dynamic>{'id': 'sme_connector', 'type': 'connector', 'refId': 'sme', 'label': 'SME Profile'},
              <String, dynamic>{'id': 'sme_gst_callback', 'type': 'action', 'label': 'GST Verification Callback', 'config': <String, dynamic>{'url': 'rulemind://simulate/sme-callback', 'method': 'POST', 'bodyTemplate': <String, dynamic>{'gstin': '{{ payload.sme.gstin }}'}, 'onFailure': 'continue'}},
              <String, dynamic>{'id': 'sme_compliance_rule', 'type': 'rule', 'refId': 'rule_sme_compliance_gate', 'label': 'Compliance Gate'},
              <String, dynamic>{'id': 'sme_census_rule', 'type': 'rule', 'refId': 'rule_sme_census_gate', 'label': 'Census Quality'},
              <String, dynamic>{'id': 'sme_risk_score', 'type': 'scorecard', 'refId': 'sc_sme_risk', 'label': 'SME Risk Score'},
              <String, dynamic>{'id': 'sme_claims_rule', 'type': 'rule', 'refId': 'rule_sme_claims_gate', 'label': 'Claims Experience'},
              <String, dynamic>{'id': 'sme_growth_rule', 'type': 'rule', 'refId': 'rule_sme_growth_gate', 'label': 'Growth Routing'},
              <String, dynamic>{'id': 'sme_review_gate', 'type': 'review_gate', 'label': 'Committee Review', 'config': <String, dynamic>{'assignTo': 'regional_risk_committee', 'requiredFields': <String>['underwriter_note'], 'condition': "outcome == 'review'"}},
              <String, dynamic>{'id': 'sme_outcome', 'type': 'outcome', 'refId': 'approve', 'label': 'Instant Quote', 'config': <String, dynamic>{'condition': "outcome != 'reject' and outcome != 'review'"}},
              <String, dynamic>{'id': 'sme_issuance_callback', 'type': 'action', 'label': 'Issuance Notice', 'config': <String, dynamic>{'url': 'rulemind://simulate/sme-issuance', 'method': 'POST', 'bodyTemplate': <String, dynamic>{'legal_company_name': '{{ payload.sme.legal_company_name }}', 'score': '{{ scorecard.sc_sme_risk.score }}'}, 'onFailure': 'continue', 'condition': "outcome == 'approve'"}},
            ],
          },
        ],
        'experiments': const <Map<String, dynamic>>[],
      });

  static Map<String, dynamic> _travelJourney() => <String, dynamic>{
        'id': 'travel_guard',
        'title': 'Travel Guard',
        'category': 'Travel Protection',
        'policyId': 'policy_travel_guard',
        'stepCount': 7,
        'primaryColor': '#496FBE',
        'screens': <Map<String, dynamic>>[
          <String, dynamic>{'id': 'travel_landing', 'title': 'Navigate Global Borders with Absolute Certainty.', 'subtitle': 'Automated trip eligibility and callback-aware verification.', 'type': 'landing', 'bullets': <String>['Passport and visa readiness', 'Destination risk overlays', 'Coverage-fit assessment']},
          <String, dynamic>{'id': 'trip_basics', 'title': 'Trip & Traveler Basics', 'subtitle': 'Provide the essential details to tailor Travel Guard protection.', 'type': 'form', 'fields': <Map<String, dynamic>>[
            _choice('destination_country', 'Destination Country', <String>['Japan', 'Portugal', 'France', 'Switzerland', 'United Arab Emirates'], required: true),
            _text('destination_city', 'City / Region', required: true),
            _number('trip_days', 'Trip Duration (Days)', required: true, min: 1),
            _choice('trip_purpose', 'Trip Purpose', <String>['Leisure', 'Business', 'Education', 'Adventure'], required: true),
            _number('primary_traveller_age', 'Primary Traveller Age', required: true, min: 18),
            _choice('citizenship', 'Citizenship', <String>['India', 'United Kingdom', 'Canada', 'United States'], required: true),
          ]},
          <String, dynamic>{'id': 'travel_readiness', 'title': 'Travel Readiness', 'subtitle': 'Ensure your documentation is in order before final eligibility assessment.', 'type': 'form', 'fields': <Map<String, dynamic>>[
            _choice('passport_status', 'Passport Availability', <String>['Currently in possession', 'In renewal process', 'Not yet applied'], required: true),
            _number('passport_months_valid', 'Passport Validity Remaining (Months)', required: true, min: 0),
            _choice('visa_status', 'Visa Status', <String>['Visa held or not required', 'Applied / Pending approval', 'Not started'], required: true),
            _choice('medical_flag', 'Medical Conditions', <String>['No material disclosures', 'Additional coverage required'], required: true),
            _choice('existing_insurance', 'Insurance Purchased?', <String>['No', 'Yes'], required: true),
          ]},
          <String, dynamic>{'id': 'coverage_preferences', 'title': 'Coverage Preferences', 'subtitle': 'Customize your coverage for total peace of mind.', 'type': 'form', 'fields': <Map<String, dynamic>>[
            _number('trip_cost_inr', 'Total Trip Cost (INR)', required: true, min: 1000),
            _choice('coverage_tier', 'Coverage Tier', <String>['Standard Protection', 'Platinum Shield'], required: true),
            _choice('medical_add_on', 'Emergency Medical', <String>['Included', 'Excluded'], required: true),
            _choice('baggage_add_on', 'Baggage Protection', <String>['Included', 'Excluded'], required: true),
          ]},
          <String, dynamic>{'id': 'travel_processing', 'title': 'Verification & Callback Processing', 'subtitle': 'Aggregating traveler verification, destination support, and policy synthesis callbacks.', 'type': 'processing'},
          <String, dynamic>{'id': 'travel_decision', 'title': 'Decision Outcome', 'subtitle': 'Premium eligibility, quote summary, rule log, and callback status.', 'type': 'outcome'},
          <String, dynamic>{'id': 'travel_audit', 'title': 'Explainability & Audit View', 'subtitle': 'Decision rationale, callback history, threshold intersections, and action plan guidance.', 'type': 'audit'},
        ],
      };

  static Map<String, dynamic> _loanJourney() => <String, dynamic>{
        'id': 'instant_personal_loan',
        'title': 'Instant Personal Loan Underwriting',
        'category': 'Credit & Loans',
        'policyId': 'policy_instant_personal_loan',
        'stepCount': 8,
        'primaryColor': '#32577F',
        'screens': <Map<String, dynamic>>[
          <String, dynamic>{'id': 'loan_landing', 'title': 'Instant Personal Loan Underwriting.', 'subtitle': 'A high-fidelity simulation of automated credit assessment in India.', 'type': 'landing', 'bullets': <String>['Bureau screening', 'Affordability analysis', 'KYC and fraud overlays']},
          <String, dynamic>{'id': 'applicant_basics', 'title': 'Applicant Basics', 'subtitle': 'Verify applicant details against regional registries and configure loan terms.', 'type': 'form', 'fields': <Map<String, dynamic>>[
            _text('full_name', 'Full Name', required: true),
            _text('mobile_number', 'Mobile Number', required: true, hint: '+91', keyboard: 'phone'),
            _text('email', 'Email Address', required: true),
            _text('pan', 'PAN', required: true),
            _choice('current_city', 'Current City', <String>['Mumbai', 'Bengaluru', 'New Delhi', 'Hyderabad', 'Pune'], required: true),
            _choice('employment_type', 'Employment Type', <String>['Salaried', 'Self-Employed'], required: true),
            _number('requested_amount_inr', 'Requested Loan Amount (INR)', required: true, min: 10000),
            _choice('requested_tenure_months', 'Requested Tenure', <String>['6', '24', '48', '60'], required: true),
          ]},
          <String, dynamic>{'id': 'income_employment', 'title': 'Income & Employment Verification', 'subtitle': 'Assess credit stability and earning potential.', 'type': 'form', 'fields': <Map<String, dynamic>>[
            _text('employer_name', 'Employer Name', required: true),
            _choice('employer_type', 'Employer Type', <String>['Private Limited', 'Public Sector', 'Government', 'Multinational'], required: true),
            _number('monthly_income_inr', 'Net Monthly Income (INR)', required: true, min: 10000),
            _choice('salary_credit_mode', 'Salary Credit Mode', <String>['Bank Transfer', 'Cheque', 'Cash'], required: true),
            _number('work_experience_years', 'Total Work Experience (Years)', required: true, min: 0),
            _number('employer_tenure_months', 'Current Employer Tenure (Months)', required: true, min: 0),
            _number('salary_account_vintage_months', 'Salary Account Vintage (Months)', required: true, min: 0),
          ]},
          <String, dynamic>{'id': 'obligations_stability', 'title': 'Obligations & Stability', 'subtitle': 'Define the borrower\'s debt profile and recurring expenditure.', 'type': 'form', 'fields': <Map<String, dynamic>>[
            _number('existing_emi_inr', 'Current EMI Obligations (INR)', required: true, min: 0),
            _number('active_loans', 'Active Loans', required: true, min: 0),
            _number('fixed_expenses_inr', 'Monthly Fixed Expenses (INR)', required: true, min: 0),
            _number('variable_expenses_inr', 'Monthly Variable Expenses (INR)', required: true, min: 0),
            _choice('residence_type', 'Residence Type', <String>['Self-Owned', 'Mortgaged / Financed', 'Rented', 'Parental / Shared'], required: true),
            _number('housing_cost_inr', 'Rent / Mortgage Amount (INR)', required: true, min: 0),
          ]},
          <String, dynamic>{'id': 'documents_identity', 'title': 'Documents & Identity Inputs', 'subtitle': 'Identity, liveness, and income proof capture.', 'type': 'form', 'fields': <Map<String, dynamic>>[
            _choice('income_proof_type', 'Income Proof Type', <String>['Form 16 / ITR V', 'Salary Certificate', 'Certified P&L'], required: true),
            _choice('utility_bill_verified', 'Utility Bill Availability', <String>['Yes, Verified', 'No / Alternative'], required: true),
            _choice('pan_verified', 'PAN Verification', <String>['Authenticated', 'Mismatch'], required: true),
            _number('liveness_score', 'Liveness Match %', required: true, min: 0, max: 100),
            _choice('geo_consistency', 'Geo Consistency', <String>['Matched', 'IP mismatch'], required: true),
          ]},
          <String, dynamic>{'id': 'loan_processing', 'title': 'External Verification & Rule Processing', 'subtitle': 'Credit bureaus, fraud services, and bank statement parsers in motion.', 'type': 'processing'},
          <String, dynamic>{'id': 'loan_offer', 'title': 'Offer Decision', 'subtitle': 'Risk band, approved amount, pricing, and underwriting rationale.', 'type': 'outcome'},
          <String, dynamic>{'id': 'loan_audit', 'title': 'Underwriting Explainability & Audit', 'subtitle': 'Conditions, callback evidence, risk drivers, and workflow trace.', 'type': 'audit'},
        ],
      };

  static Map<String, dynamic> _smeJourney() => <String, dynamic>{
        'id': 'sme_underwriting',
        'title': 'SME Insurance, Compliance & Underwriting Workflow',
        'category': 'SME Business',
        'policyId': 'policy_sme_underwriting',
        'stepCount': 10,
        'primaryColor': '#294860',
        'screens': <Map<String, dynamic>>[
          <String, dynamic>{'id': 'sme_landing', 'title': 'SME Insurance, Compliance & Underwriting Workflow', 'subtitle': 'Automated risk triage from instant quote to committee review using India-ready business inputs.', 'type': 'landing', 'bullets': <String>['KYB & sanctions', 'Census quality', 'Claims & compliance routing']},
          <String, dynamic>{'id': 'business_onboarding', 'title': 'Business Onboarding', 'subtitle': 'Core registration information as listed on official documents.', 'type': 'form', 'fields': <Map<String, dynamic>>[
            _text('legal_company_name', 'Legal Company Name', required: true),
            _text('trade_name', 'Trade Name'),
            _choice('incorporation_type', 'Incorporation Type', <String>['Private Limited', 'Public Limited', 'LLP', 'Partnership', 'Sole Proprietorship'], required: true),
            _choice('industry_segment', 'Industry Segment', <String>['Software & Technology', 'Manufacturing', 'Logistics', 'Retail & FMCG', 'Healthcare'], required: true),
            _text('gstin', 'GSTIN', required: true),
            _text('company_pan', 'Company PAN', required: true),
            _number('years_in_business', 'Years in Business', required: true, min: 0),
            _number('employee_count', 'Employee Count', required: true, min: 1),
            _text('headquarters_city', 'Headquarters City', required: true),
          ]},
          <String, dynamic>{'id': 'coverage_design', 'title': 'Coverage Design', 'subtitle': 'Configure sum insured, policy structure, add-ons, and internal underwriting notes.', 'type': 'form', 'fields': <Map<String, dynamic>>[
            _number('sum_insured_inr', 'Sum Insured (INR)', required: true, min: 500000),
            _choice('policy_type', 'Policy Type', <String>['Family Floater', 'Individual'], required: true),
            _choice('dependent_inclusion', 'Dependent Inclusion', <String>['Spouse', 'Children', 'Parents'], required: true, multi: true),
            _choice('deductible', 'Deductible', <String>['No Limit', '1% of Sum Insured', 'Single Private Room'], required: true),
            _choice('maternity_benefit', 'Maternity Benefit', <String>['Enabled', 'Disabled'], required: true),
            _number('estimated_premium_inr', 'Estimated Annual Premium (INR)', required: true, min: 10000),
          ]},
          <String, dynamic>{'id': 'employee_census', 'title': 'Employee Census Intake', 'subtitle': 'Participant data collection, validation, and census-quality preview.', 'type': 'form', 'fields': <Map<String, dynamic>>[
            _number('census_record_count', 'Total Records', required: true, min: 1),
            _number('census_validation_errors', 'Validation Errors', required: true, min: 0),
            _number('census_duplicate_hits', 'Duplicate Hits', required: true, min: 0),
            _number('census_quality_score', 'Accuracy Score', required: true, min: 0, max: 100),
            _number('median_age', 'Median Employee Age', required: true, min: 18),
          ]},
          <String, dynamic>{'id': 'prior_policy_claims', 'title': 'Prior Policy & Claims Experience', 'subtitle': 'Historical insurer, claims, exclusions, and loss-ratio profile.', 'type': 'form', 'fields': <Map<String, dynamic>>[
            _choice('policy_type', 'Policy Type', <String>['Renewal', 'Fresh'], required: true),
            _choice('existing_insurer', 'Existing Insurer', <String>['ICICI Lombard', 'AXA XL', 'Allianz', 'HDFC ERGO', 'Chubb'], required: true),
            _number('claims_count', 'Claims Count', required: true, min: 0),
            _number('loss_ratio_pct', 'Loss Ratio %', required: true, min: 0),
            _number('large_losses', 'Large Losses', required: true, min: 0),
            _choice('claims_disclosed', 'Claims Fully Disclosed', <String>['Yes', 'No'], required: true),
          ]},
          <String, dynamic>{'id': 'compliance_documents', 'title': 'Compliance Documents', 'subtitle': 'Corporate identity, claims reports, census, and signed declaration readiness.', 'type': 'form', 'fields': <Map<String, dynamic>>[
            _choice('coi_uploaded', 'Certificate of Incorporation', <String>['Uploaded', 'Missing'], required: true),
            _choice('pan_uploaded', 'Company PAN', <String>['Uploaded', 'Missing'], required: true),
            _choice('claims_report_uploaded', 'Claims Report', <String>['Uploaded', 'Missing'], required: true),
            _choice('signed_declaration_uploaded', 'Signed Declaration', <String>['Uploaded', 'Missing'], required: true),
            _choice('ubo_docs_ready', 'UBO Documentation', <String>['Ready', 'Pending'], required: true),
          ]},
          <String, dynamic>{'id': 'sme_processing', 'title': 'External Verification & Parsing', 'subtitle': 'OCR, GST callback, anomaly detection, sanctions screening, and wait-state orchestration.', 'type': 'processing'},
          <String, dynamic>{'id': 'sme_routing', 'title': 'Underwriting, Compliance & Routing Evaluation', 'subtitle': 'Support-guideline checks, fraud heuristics, and routing preview.', 'type': 'processing'},
          <String, dynamic>{'id': 'sme_outcome', 'title': 'Final Outcome', 'subtitle': 'Instant quote, underwriter review, or compliance hold with conditions and blockers.', 'type': 'outcome'},
          <String, dynamic>{'id': 'sme_audit', 'title': 'Full Explainability, Audit & Workflow Trace', 'subtitle': 'Decision blockers, callback evidence, actor trail, and remediation guidance.', 'type': 'audit'},
        ],
      };

  static List<Map<String, dynamic>> _travelScenarios() => <Map<String, dynamic>>[
        <String, dynamic>{'id': 'travel_happy_path', 'journeyId': 'travel_guard', 'title': 'Happy Path Traveler', 'badge': 'Low Risk', 'expectedOutcome': 'approve', 'expectedStatus': 'completed', 'payload': <String, dynamic>{'travel': <String, dynamic>{'destination_country': 'Portugal', 'destination_city': 'Lisbon', 'trip_days': 10, 'trip_purpose': 'Leisure', 'primary_traveller_age': 34, 'citizenship': 'India', 'passport_status': 'Currently in possession', 'passport_months_valid': 14, 'visa_status': 'Visa held or not required', 'medical_flag': 'No material disclosures', 'existing_insurance': 'No', 'trip_cost_inr': 145000, 'coverage_tier': 'Standard Protection', 'medical_add_on': 'Included', 'baggage_add_on': 'Included', 'destination_risk': 1, 'visa_ready': 1, 'support_matrix_ready': 1, 'medical_flag_value': 0}}},
        <String, dynamic>{'id': 'travel_senior_review', 'journeyId': 'travel_guard', 'title': 'Senior Traveler Review', 'badge': 'Manual Review', 'expectedOutcome': 'review', 'expectedStatus': 'paused', 'payload': <String, dynamic>{'travel': <String, dynamic>{'destination_country': 'Japan', 'destination_city': 'Osaka', 'trip_days': 14, 'trip_purpose': 'Leisure', 'primary_traveller_age': 77, 'citizenship': 'India', 'passport_status': 'Currently in possession', 'passport_months_valid': 11, 'visa_status': 'Visa held or not required', 'medical_flag': 'Additional coverage required', 'existing_insurance': 'Yes', 'trip_cost_inr': 220000, 'coverage_tier': 'Platinum Shield', 'medical_add_on': 'Included', 'baggage_add_on': 'Included', 'destination_risk': 2, 'visa_ready': 1, 'support_matrix_ready': 1, 'medical_flag_value': 1}}},
        <String, dynamic>{'id': 'travel_passport_failure', 'journeyId': 'travel_guard', 'title': 'Passport Validity Failure', 'badge': 'Critical', 'expectedOutcome': 'reject', 'expectedStatus': 'completed', 'payload': <String, dynamic>{'travel': <String, dynamic>{'destination_country': 'France', 'destination_city': 'Paris', 'trip_days': 7, 'trip_purpose': 'Leisure', 'primary_traveller_age': 29, 'citizenship': 'India', 'passport_status': 'Currently in possession', 'passport_months_valid': 2, 'visa_status': 'Visa held or not required', 'medical_flag': 'No material disclosures', 'existing_insurance': 'No', 'trip_cost_inr': 98000, 'coverage_tier': 'Standard Protection', 'medical_add_on': 'Included', 'baggage_add_on': 'Included', 'destination_risk': 1, 'visa_ready': 1, 'support_matrix_ready': 1, 'medical_flag_value': 0}}},
      ];

  static List<Map<String, dynamic>> _loanScenarios() => <Map<String, dynamic>>[
        <String, dynamic>{'id': 'loan_prime_approved', 'journeyId': 'instant_personal_loan', 'title': 'Prime Borrower Approved', 'badge': 'Happy Path', 'expectedOutcome': 'approve', 'expectedStatus': 'completed', 'payload': <String, dynamic>{'loan': <String, dynamic>{'full_name': 'Aarav Mehta', 'mobile_number': '9876543210', 'email': 'aarav.mehta@example.in', 'pan': 'ABCDE1234F', 'current_city': 'Mumbai', 'employment_type': 'Salaried', 'requested_amount_inr': 850000, 'requested_tenure_months': 48, 'employer_name': 'Axis Advisory Services', 'employer_type': 'Multinational', 'monthly_income_inr': 185000, 'salary_credit_mode': 'Bank Transfer', 'work_experience_years': 9, 'employer_tenure_months': 42, 'salary_account_vintage_months': 48, 'existing_emi_inr': 12000, 'active_loans': 1, 'fixed_expenses_inr': 18000, 'variable_expenses_inr': 22000, 'residence_type': 'Self-Owned', 'housing_cost_inr': 0, 'income_proof_type': 'Form 16 / ITR V', 'utility_bill_verified': 'Yes, Verified', 'pan_verified': 'Authenticated', 'liveness_score': 98.4, 'geo_consistency': 'Matched', 'bureau_score': 756, 'avg_balance_inr': 124000, 'dti_ratio': 0.16, 'pan_verified_flag': 1, 'geo_consistency_flag': 0}}},
        <String, dynamic>{'id': 'loan_borderline_review', 'journeyId': 'instant_personal_loan', 'title': 'Borderline Borrower', 'badge': 'Review', 'expectedOutcome': 'review', 'expectedStatus': 'paused', 'payload': <String, dynamic>{'loan': <String, dynamic>{'full_name': 'Rhea Kapoor', 'mobile_number': '9898989898', 'email': 'rhea.kapoor@example.in', 'pan': 'PQRSK4567L', 'current_city': 'Pune', 'employment_type': 'Salaried', 'requested_amount_inr': 550000, 'requested_tenure_months': 60, 'employer_name': 'Nextline Retail', 'employer_type': 'Private Limited', 'monthly_income_inr': 72000, 'salary_credit_mode': 'Bank Transfer', 'work_experience_years': 4, 'employer_tenure_months': 10, 'salary_account_vintage_months': 16, 'existing_emi_inr': 14000, 'active_loans': 2, 'fixed_expenses_inr': 18000, 'variable_expenses_inr': 13000, 'residence_type': 'Rented', 'housing_cost_inr': 18000, 'income_proof_type': 'Salary Certificate', 'utility_bill_verified': 'Yes, Verified', 'pan_verified': 'Authenticated', 'liveness_score': 95.0, 'geo_consistency': 'Matched', 'bureau_score': 688, 'avg_balance_inr': 28000, 'dti_ratio': 0.44, 'pan_verified_flag': 1, 'geo_consistency_flag': 0}}},
        <String, dynamic>{'id': 'loan_high_foir_reject', 'journeyId': 'instant_personal_loan', 'title': 'High FOIR Reject', 'badge': 'Reject', 'expectedOutcome': 'reject', 'expectedStatus': 'completed', 'payload': <String, dynamic>{'loan': <String, dynamic>{'full_name': 'Kunal Sharma', 'mobile_number': '9123456780', 'email': 'kunal.sharma@example.in', 'pan': 'ZXCVB9876Q', 'current_city': 'Hyderabad', 'employment_type': 'Salaried', 'requested_amount_inr': 450000, 'requested_tenure_months': 36, 'employer_name': 'Urban Fleet Labs', 'employer_type': 'Private Limited', 'monthly_income_inr': 58000, 'salary_credit_mode': 'Bank Transfer', 'work_experience_years': 3, 'employer_tenure_months': 9, 'salary_account_vintage_months': 12, 'existing_emi_inr': 24000, 'active_loans': 3, 'fixed_expenses_inr': 12000, 'variable_expenses_inr': 9000, 'residence_type': 'Rented', 'housing_cost_inr': 16000, 'income_proof_type': 'Form 16 / ITR V', 'utility_bill_verified': 'Yes, Verified', 'pan_verified': 'Authenticated', 'liveness_score': 97.0, 'geo_consistency': 'Matched', 'bureau_score': 702, 'avg_balance_inr': 19000, 'dti_ratio': 0.62, 'pan_verified_flag': 1, 'geo_consistency_flag': 0}}},
        <String, dynamic>{'id': 'loan_fraud_review', 'journeyId': 'instant_personal_loan', 'title': 'Fraud Review Case', 'badge': 'Fraud Overlay', 'expectedOutcome': 'review', 'expectedStatus': 'paused', 'payload': <String, dynamic>{'loan': <String, dynamic>{'full_name': 'Meera Sethi', 'mobile_number': '9988776655', 'email': 'meera.sethi@example.in', 'pan': 'LMNOP4321K', 'current_city': 'Bengaluru', 'employment_type': 'Salaried', 'requested_amount_inr': 980000, 'requested_tenure_months': 48, 'employer_name': 'Cloud Meridian', 'employer_type': 'Multinational', 'monthly_income_inr': 210000, 'salary_credit_mode': 'Bank Transfer', 'work_experience_years': 7, 'employer_tenure_months': 30, 'salary_account_vintage_months': 32, 'existing_emi_inr': 8000, 'active_loans': 1, 'fixed_expenses_inr': 15000, 'variable_expenses_inr': 18000, 'residence_type': 'Self-Owned', 'housing_cost_inr': 0, 'income_proof_type': 'Form 16 / ITR V', 'utility_bill_verified': 'Yes, Verified', 'pan_verified': 'Authenticated', 'liveness_score': 96.0, 'geo_consistency': 'IP mismatch', 'bureau_score': 741, 'avg_balance_inr': 96000, 'dti_ratio': 0.18, 'pan_verified_flag': 1, 'geo_consistency_flag': 1}}},
        <String, dynamic>{'id': 'loan_kyc_reject', 'journeyId': 'instant_personal_loan', 'title': 'KYC Mismatch Reject', 'badge': 'KYC Mismatch', 'expectedOutcome': 'reject', 'expectedStatus': 'completed', 'payload': <String, dynamic>{'loan': <String, dynamic>{'full_name': 'Ishita Nair', 'mobile_number': '9811122233', 'email': 'ishita.nair@example.in', 'pan': 'AAAPA1122P', 'current_city': 'Mumbai', 'employment_type': 'Salaried', 'requested_amount_inr': 620000, 'requested_tenure_months': 24, 'employer_name': 'Marina Commerce', 'employer_type': 'Private Limited', 'monthly_income_inr': 98000, 'salary_credit_mode': 'Bank Transfer', 'work_experience_years': 5, 'employer_tenure_months': 18, 'salary_account_vintage_months': 22, 'existing_emi_inr': 9000, 'active_loans': 1, 'fixed_expenses_inr': 14000, 'variable_expenses_inr': 16000, 'residence_type': 'Rented', 'housing_cost_inr': 22000, 'income_proof_type': 'Form 16 / ITR V', 'utility_bill_verified': 'No / Alternative', 'pan_verified': 'Mismatch', 'liveness_score': 82.0, 'geo_consistency': 'Matched', 'bureau_score': 730, 'avg_balance_inr': 48000, 'dti_ratio': 0.24, 'pan_verified_flag': 0, 'geo_consistency_flag': 0}}},
      ];

  static List<Map<String, dynamic>> _smeScenarios() => <Map<String, dynamic>>[
        <String, dynamic>{'id': 'sme_instant_quote', 'journeyId': 'sme_underwriting', 'title': 'Clean SME Instant Quote', 'badge': 'Auto-rate', 'expectedOutcome': 'approve', 'expectedStatus': 'completed', 'payload': <String, dynamic>{'sme': <String, dynamic>{'legal_company_name': 'Apex Logistics Private Limited', 'trade_name': 'Apex Logistics', 'incorporation_type': 'Private Limited', 'industry_segment': 'Logistics', 'gstin': '27AAACA1234F1Z5', 'company_pan': 'AAACA1234F', 'years_in_business': 8, 'employee_count': 124, 'headquarters_city': 'Mumbai', 'sum_insured_inr': 10000000, 'policy_type': 'Family Floater', 'dependent_inclusion': <String>['Spouse', 'Children'], 'deductible': '1% of Sum Insured', 'maternity_benefit': 'Enabled', 'estimated_premium_inr': 142500, 'census_record_count': 1248, 'census_validation_errors': 4, 'census_duplicate_hits': 1, 'census_quality_score': 96.0, 'median_age': 34.2, 'existing_insurer': 'ICICI Lombard', 'claims_count': 1, 'loss_ratio_pct': 14.5, 'large_losses': 0, 'claims_disclosed': 'Yes', 'coi_uploaded': 'Uploaded', 'pan_uploaded': 'Uploaded', 'claims_report_uploaded': 'Uploaded', 'signed_declaration_uploaded': 'Uploaded', 'ubo_docs_ready': 'Ready', 'gst_compliance_score': 94, 'sanctions_flag': 0, 'growth_rate_pct': 18, 'ubo_docs_ready_flag': 1, 'claims_disclosed_flag': 1}}},
        <String, dynamic>{'id': 'sme_claims_review', 'journeyId': 'sme_underwriting', 'title': 'High Claims Ratio Review', 'badge': 'Review', 'expectedOutcome': 'review', 'expectedStatus': 'paused', 'payload': <String, dynamic>{'sme': <String, dynamic>{'legal_company_name': 'Lumina Craft Brewery LLP', 'trade_name': 'Lumina Craft Brewery', 'incorporation_type': 'LLP', 'industry_segment': 'Manufacturing', 'gstin': '29AAACL7788P1Z4', 'company_pan': 'AAACL7788P', 'years_in_business': 5, 'employee_count': 86, 'headquarters_city': 'Bengaluru', 'sum_insured_inr': 25000000, 'policy_type': 'Individual', 'dependent_inclusion': <String>['Spouse'], 'deductible': 'No Limit', 'maternity_benefit': 'Disabled', 'estimated_premium_inr': 268000, 'census_record_count': 860, 'census_validation_errors': 18, 'census_duplicate_hits': 4, 'census_quality_score': 88.0, 'median_age': 37.0, 'existing_insurer': 'AXA XL', 'claims_count': 12, 'loss_ratio_pct': 42.8, 'large_losses': 1, 'claims_disclosed': 'Yes', 'coi_uploaded': 'Uploaded', 'pan_uploaded': 'Uploaded', 'claims_report_uploaded': 'Uploaded', 'signed_declaration_uploaded': 'Uploaded', 'ubo_docs_ready': 'Ready', 'gst_compliance_score': 86, 'sanctions_flag': 0, 'growth_rate_pct': 72, 'ubo_docs_ready_flag': 1, 'claims_disclosed_flag': 1}}},
        <String, dynamic>{'id': 'sme_census_failure', 'journeyId': 'sme_underwriting', 'title': 'Census Quality Failure', 'badge': 'Clarification', 'expectedOutcome': 'review', 'expectedStatus': 'paused', 'payload': <String, dynamic>{'sme': <String, dynamic>{'legal_company_name': 'Northwind Health Services LLP', 'trade_name': 'Northwind Health', 'incorporation_type': 'LLP', 'industry_segment': 'Healthcare', 'gstin': '07AAACN3322D1Z7', 'company_pan': 'AAACN3322D', 'years_in_business': 6, 'employee_count': 220, 'headquarters_city': 'New Delhi', 'sum_insured_inr': 18000000, 'policy_type': 'Family Floater', 'dependent_inclusion': <String>['Spouse', 'Children', 'Parents'], 'deductible': '1% of Sum Insured', 'maternity_benefit': 'Enabled', 'estimated_premium_inr': 312000, 'census_record_count': 1180, 'census_validation_errors': 114, 'census_duplicate_hits': 26, 'census_quality_score': 72.0, 'median_age': 38.5, 'existing_insurer': 'HDFC ERGO', 'claims_count': 4, 'loss_ratio_pct': 26.0, 'large_losses': 0, 'claims_disclosed': 'Yes', 'coi_uploaded': 'Uploaded', 'pan_uploaded': 'Uploaded', 'claims_report_uploaded': 'Uploaded', 'signed_declaration_uploaded': 'Uploaded', 'ubo_docs_ready': 'Ready', 'gst_compliance_score': 90, 'sanctions_flag': 0, 'growth_rate_pct': 21, 'ubo_docs_ready_flag': 1, 'claims_disclosed_flag': 1}}},
        <String, dynamic>{'id': 'sme_compliance_hold', 'journeyId': 'sme_underwriting', 'title': 'Compliance Hold', 'badge': 'PEP Match Alert', 'expectedOutcome': 'review', 'expectedStatus': 'paused', 'payload': <String, dynamic>{'sme': <String, dynamic>{'legal_company_name': 'Global Tech Solutions Private Limited', 'trade_name': 'Global Tech Solutions', 'incorporation_type': 'Private Limited', 'industry_segment': 'Software & Technology', 'gstin': '27AAACG5555Q1Z3', 'company_pan': 'AAACG5555Q', 'years_in_business': 4, 'employee_count': 64, 'headquarters_city': 'Pune', 'sum_insured_inr': 12500000, 'policy_type': 'Individual', 'dependent_inclusion': <String>['Spouse'], 'deductible': 'No Limit', 'maternity_benefit': 'Enabled', 'estimated_premium_inr': 198000, 'census_record_count': 642, 'census_validation_errors': 8, 'census_duplicate_hits': 1, 'census_quality_score': 94.0, 'median_age': 31.8, 'existing_insurer': 'ICICI Lombard', 'claims_count': 1, 'loss_ratio_pct': 12.0, 'large_losses': 0, 'claims_disclosed': 'Yes', 'coi_uploaded': 'Uploaded', 'pan_uploaded': 'Uploaded', 'claims_report_uploaded': 'Uploaded', 'signed_declaration_uploaded': 'Uploaded', 'ubo_docs_ready': 'Pending', 'gst_compliance_score': 91, 'sanctions_flag': 1, 'growth_rate_pct': 420, 'ubo_docs_ready_flag': 0, 'claims_disclosed_flag': 1}}},
      ];

  static Map<String, dynamic> _entity(String id, String title, String listPath, String detailPath, {String? createPath, String? updatePath, String? testPath, bool supportsCreate = false, bool supportsDelete = false, bool supportsPromote = false, required List<Map<String, dynamic>> fields}) => <String, dynamic>{
        'id': id,
        'title': title,
        'listPath': listPath,
        'detailPath': detailPath,
        'createPath': createPath,
        'updatePath': updatePath,
        'testPath': testPath,
        'supportsCreate': supportsCreate,
        'supportsDelete': supportsDelete,
        'supportsPromote': supportsPromote,
        'fields': fields,
      };

  static Map<String, dynamic> _text(String id, String label, {bool required = false, String hint = '', String keyboard = 'text'}) => <String, dynamic>{'id': id, 'label': label, 'kind': 'text', 'required': required, 'hint': hint, 'keyboard': keyboard};
  static Map<String, dynamic> _number(String id, String label, {bool required = false, num? min, num? max}) => <String, dynamic>{'id': id, 'label': label, 'kind': 'number', 'required': required, 'keyboard': 'number', 'min': min, 'max': max};
  static Map<String, dynamic> _choice(String id, String label, List<String> options, {bool required = false, bool multi = false}) => <String, dynamic>{'id': id, 'label': label, 'kind': 'choice', 'required': required, 'options': options, 'multi': multi};
  static Map<String, dynamic> _jsonField(String id, String label) => <String, dynamic>{'id': id, 'label': label, 'kind': 'json'};
  static Map<String, dynamic> _boolField(String id, String label) => <String, dynamic>{'id': id, 'label': label, 'kind': 'boolean'};
  static Map<String, dynamic> _codeField(String id, String label, {bool required = false}) => <String, dynamic>{'id': id, 'label': label, 'kind': 'code', 'required': required, 'language': 'python'};

  static Map<String, dynamic> _variable(String id, String sourceId, String name, String path) => <String, dynamic>{
        'id': id,
        'sourceId': sourceId,
        'name': name,
        'returnType': 'number',
        'compilable': true,
        'instructions': <Map<String, dynamic>>[
          <String, dynamic>{'op': 'get', 'source': 'payload', 'path': '$sourceId.$path', 'target': 'result'},
          <String, dynamic>{'op': 'return', 'source': 'result'},
        ],
      };

  static Map<String, dynamic> _condition(String variable, String operator, Object value) => <String, dynamic>{'type': 'condition', 'variable': variable, 'operator': operator, 'value': value};
  static Map<String, dynamic> _rule(String id, String name, String onPass, String onFail, List<Map<String, dynamic>> conditions) => <String, dynamic>{'id': id, 'name': name, 'ruleFormat': 'v2', 'tree': <String, dynamic>{'type': 'group', 'id': '${id}_root', 'logic': 'AND', 'children': conditions, 'onPass': onPass, 'onFail': onFail}, 'nodes': const <Map<String, dynamic>>[]};
  static Map<String, dynamic> _scorecard(String id, String name, int baseScore, List<Map<String, dynamic>> bins) => <String, dynamic>{'id': id, 'name': name, 'baseScore': baseScore, 'maxScore': 900, 'bins': bins};
  static Map<String, dynamic> _factor(String variableId, List<Map<String, dynamic>> ranges) => <String, dynamic>{'variableId': variableId, 'ranges': ranges};
  static Map<String, dynamic> _range(num min, num max, int points) => <String, dynamic>{'min': min, 'max': max, 'points': points};
}
