import "models.dart";

Decision decisionFromMap(Map<String, dynamic> raw) {
  final experiment = raw["experiment"] as Map<String, dynamic>?;
  return Decision(
    outcome: raw["outcome"] as String,
    score: (raw["score"] as num?)?.toDouble(),
    variables: Map<String, dynamic>.from(raw["variables"] as Map? ?? const <String, dynamic>{}),
    ruleResults: ((raw["ruleResults"] as List<dynamic>? ?? const <dynamic>[]).whereType<Map>().map((item) => Map<String, dynamic>.from(item)).toList()),
    experimentId: raw["experimentId"] as String? ?? experiment?["id"] as String?,
    experimentVariant: raw["experimentVariant"] as String? ?? experiment?["variant"] as String?,
    latencyMs: (raw["latencyMs"] as num?)?.toInt() ?? 0,
    requestId: raw["requestId"] as String?,
    serverOnlyStepsSkipped: (raw["serverOnlyStepsSkipped"] as List<dynamic>? ?? const <dynamic>[]).map((item) => item.toString()).toList(),
    executionId: raw["executionId"] as String?,
    status: raw["status"]?.toString() ?? "completed",
    trace: ((raw["trace"] as List<dynamic>? ?? const <dynamic>[]).whereType<Map>().map((item) => Map<String, dynamic>.from(item)).toList()),
    scorecardResults: ((raw["scorecardResults"] as Map?) ?? const <String, dynamic>{}).map((key, value) => MapEntry(key.toString(), Map<String, dynamic>.from(value as Map? ?? const <String, dynamic>{}))),
    actionResults: ((raw["actionResults"] as List<dynamic>? ?? const <dynamic>[]).whereType<Map>().map((item) => Map<String, dynamic>.from(item)).toList()),
    pendingOperations: ((raw["pendingOperations"] as List<dynamic>? ?? const <dynamic>[]).whereType<Map>().map((item) => Map<String, dynamic>.from(item)).toList()),
    reviewTask: raw["reviewTask"] is Map ? Map<String, dynamic>.from(raw["reviewTask"] as Map) : null,
    explainability: Map<String, dynamic>.from(raw["explainability"] as Map? ?? const <String, dynamic>{}),
    auditSummary: Map<String, dynamic>.from(raw["auditSummary"] as Map? ?? const <String, dynamic>{}),
    source: raw["source"]?.toString(),
    policyId: raw["policyId"]?.toString(),
    userId: raw["userId"]?.toString(),
    payload: Map<String, dynamic>.from(raw["payload"] as Map? ?? const <String, dynamic>{}),
    transformOutputs: ((raw["transformOutputs"] as Map?) ?? const <String, dynamic>{}).map((key, value) => MapEntry(key.toString(), Map<String, dynamic>.from(value as Map? ?? const <String, dynamic>{}))),
    currentStepIndex: (raw["currentStepIndex"] as num?)?.toInt() ?? 0,
    pausedAtStep: (raw["pausedAtStep"] as num?)?.toInt(),
    reviewResponse: Map<String, dynamic>.from(raw["reviewResponse"] as Map? ?? const <String, dynamic>{}),
  );
}

Map<String, dynamic> decisionToMap(Decision decision) => <String, dynamic>{
      "outcome": decision.outcome,
      "score": decision.score,
      "variables": decision.variables,
      "ruleResults": decision.ruleResults,
      "experimentId": decision.experimentId,
      "experimentVariant": decision.experimentVariant,
      "latencyMs": decision.latencyMs,
      "requestId": decision.requestId,
      "serverOnlyStepsSkipped": decision.serverOnlyStepsSkipped,
      "executionId": decision.executionId,
      "status": decision.status,
      "trace": decision.trace,
      "scorecardResults": decision.scorecardResults,
      "actionResults": decision.actionResults,
      "pendingOperations": decision.pendingOperations,
      "reviewTask": decision.reviewTask,
      "explainability": decision.explainability,
      "auditSummary": decision.auditSummary,
      "source": decision.source,
      "policyId": decision.policyId,
      "userId": decision.userId,
      "payload": decision.payload,
      "transformOutputs": decision.transformOutputs,
      "currentStepIndex": decision.currentStepIndex,
      "pausedAtStep": decision.pausedAtStep,
      "reviewResponse": decision.reviewResponse,
    };
