from __future__ import annotations

import copy
from typing import Any, Dict, List


def _text_field(field_id: str, label: str, *, hint: str = "", required: bool = False, keyboard: str = "text") -> Dict[str, Any]:
    return {
        "id": field_id,
        "label": label,
        "kind": "text",
        "hint": hint,
        "required": required,
        "keyboard": keyboard,
    }


def _number_field(field_id: str, label: str, *, hint: str = "", required: bool = False, min_value: float | None = None, max_value: float | None = None) -> Dict[str, Any]:
    payload = _text_field(field_id, label, hint=hint, required=required, keyboard="number")
    payload["kind"] = "number"
    if min_value is not None:
        payload["min"] = min_value
    if max_value is not None:
        payload["max"] = max_value
    return payload


def _choice_field(field_id: str, label: str, options: List[str], *, required: bool = False, multi: bool = False) -> Dict[str, Any]:
    return {
        "id": field_id,
        "label": label,
        "kind": "choice",
        "required": required,
        "multi": multi,
        "options": options,
    }


def _json_field(field_id: str, label: str, *, required: bool = False) -> Dict[str, Any]:
    return {
        "id": field_id,
        "label": label,
        "kind": "json",
        "required": required,
    }


ADMIN_ENTITY_SCHEMAS: List[Dict[str, Any]] = [
    {
        "id": "connectors",
        "title": "Connectors",
        "listPath": "/api/v1/connectors",
        "detailPath": "/api/v1/connectors/{id}",
        "createPath": "/api/v1/connectors",
        "updatePath": "/api/v1/connectors/{id}",
        "testPath": "/api/v1/connectors/{id}/test",
        "supportsCreate": True,
        "supportsDelete": True,
        "supportsPromote": False,
        "fields": [
            _text_field("name", "Name", required=True),
            _text_field("icon", "Icon"),
            _text_field("color", "Color"),
            _text_field("description", "Description"),
            _json_field("schema_paths", "Schema Paths"),
            _json_field("sample_payload", "Sample Payload"),
            {"id": "is_active", "label": "Active", "kind": "boolean"},
            _json_field("config", "Configuration"),
        ],
    },
    {
        "id": "variables",
        "title": "Variables",
        "listPath": "/api/v1/variables",
        "detailPath": "/api/v1/variables/{id}",
        "createPath": "/api/v1/variables",
        "updatePath": "/api/v1/variables/{id}",
        "testPath": "/api/v1/variables/{id}/test",
        "draftTestPath": "/api/v1/variables/test-draft",
        "supportsCreate": True,
        "supportsDelete": True,
        "supportsPromote": True,
        "fields": [
            _text_field("name", "Name", required=True),
            _text_field("category", "Category", required=True),
            _text_field("source_id", "Source ID", required=True),
            _choice_field("status", "Status", ["dev", "uat", "prod"], required=True),
            _text_field("description", "Description"),
            {"id": "code", "label": "Code", "kind": "code", "language": "python", "required": True},
        ],
    },
    {
        "id": "rules",
        "title": "Rules",
        "listPath": "/api/v1/rules",
        "detailPath": "/api/v1/rules/{id}",
        "createPath": "/api/v1/rules",
        "updatePath": "/api/v1/rules/{id}",
        "testPath": "/api/v1/rules/{id}/test",
        "supportsCreate": True,
        "supportsDelete": True,
        "supportsPromote": True,
        "fields": [
            _text_field("name", "Name", required=True),
            _choice_field("ruleFormat", "Rule Format", ["v1", "v2"], required=True),
            _choice_field("status", "Status", ["dev", "uat", "prod"], required=True),
            _json_field("nodes", "Nodes"),
            _json_field("tree", "Tree"),
        ],
    },
    {
        "id": "scorecards",
        "title": "Scorecards",
        "listPath": "/api/v1/scorecards",
        "detailPath": "/api/v1/scorecards/{id}",
        "createPath": "/api/v1/scorecards",
        "updatePath": "/api/v1/scorecards/{id}",
        "testPath": "/api/v1/scorecards/{id}/test",
        "supportsCreate": True,
        "supportsDelete": True,
        "supportsPromote": True,
        "fields": [
            _text_field("name", "Name", required=True),
            _number_field("base_score", "Base Score", required=True),
            _number_field("max_score", "Max Score", required=True),
            _choice_field("status", "Status", ["dev", "uat", "prod"], required=True),
            _json_field("bins", "Bins"),
        ],
    },
    {
        "id": "policies",
        "title": "Policies",
        "listPath": "/api/v1/policies",
        "detailPath": "/api/v1/policies/{id}",
        "createPath": "/api/v1/policies",
        "updatePath": "/api/v1/policies/{id}",
        "testPath": "/api/v1/policies/{id}/execute",
        "supportsCreate": True,
        "supportsDelete": True,
        "supportsPromote": True,
        "fields": [
            _text_field("name", "Name", required=True),
            _choice_field("status", "Status", ["dev", "uat", "prod"], required=True),
            _text_field("defaultOutcome", "Default Outcome"),
            _json_field("trigger", "Trigger"),
            _json_field("steps", "Steps"),
        ],
    },
    {
        "id": "experiments",
        "title": "Experiments",
        "listPath": "/api/v1/experiments",
        "detailPath": "/api/v1/experiments/{id}",
        "createPath": "/api/v1/experiments",
        "updatePath": "/api/v1/experiments/{id}",
        "supportsCreate": True,
        "supportsDelete": True,
        "supportsPromote": False,
        "fields": [
            _text_field("name", "Name", required=True),
            _text_field("description", "Description"),
            _text_field("target_policy_id", "Target Policy ID"),
            _text_field("hash_key", "Hash Key"),
            _choice_field("status", "Status", ["draft", "running", "paused", "stopped"], required=True),
            _json_field("variants", "Variants"),
        ],
    },
    {
        "id": "webhooks",
        "title": "Webhooks",
        "listPath": "/api/v1/webhooks",
        "detailPath": "/api/v1/webhooks/{id}",
        "createPath": "/api/v1/webhooks",
        "updatePath": "/api/v1/webhooks/{id}",
        "testPath": "/api/v1/webhooks/{id}/test",
        "supportsCreate": True,
        "supportsDelete": True,
        "supportsPromote": False,
        "fields": [
            _text_field("policy_id", "Policy ID", required=True),
            {"id": "is_active", "label": "Active", "kind": "boolean"},
            _text_field("secret", "Secret"),
            _json_field("payload_mapping", "Payload Mapping"),
        ],
    },
    {
        "id": "schedules",
        "title": "Schedules",
        "listPath": "/api/v1/schedules",
        "detailPath": "/api/v1/schedules/{id}",
        "createPath": "/api/v1/schedules",
        "updatePath": "/api/v1/schedules/{id}",
        "testPath": "/api/v1/schedules/{id}/run-now",
        "supportsCreate": True,
        "supportsDelete": True,
        "supportsPromote": False,
        "fields": [
            _text_field("policy_id", "Policy ID", required=True),
            _text_field("cron_expression", "Cron Expression", required=True),
            {"id": "is_active", "label": "Active", "kind": "boolean"},
            _json_field("payload_source", "Payload Source"),
            _json_field("config", "Configuration"),
        ],
    },
    {
        "id": "settings",
        "title": "Settings",
        "listPath": "/api/v1/settings",
        "detailPath": "/api/v1/settings",
        "updatePath": "/api/v1/settings",
        "supportsCreate": False,
        "supportsDelete": False,
        "supportsPromote": False,
        "fields": [
            _text_field("api_base_url", "API Base URL"),
            _json_field("auth_config", "Auth Configuration"),
            _json_field("engine_config", "Engine Configuration"),
            _json_field("source_defaults", "Source Defaults"),
            _number_field("audit_retention_days", "Audit Retention Days"),
            _choice_field("theme_mode", "Theme Mode", ["light", "dark"]),
        ],
    },
]


EXPERIENCE_MANIFEST_TEMPLATE: Dict[str, Any] = {
    "version": "2026.04.01",
    "locale": "en-IN",
    "design": {
        "themeId": "rulemind_slate_steel",
        "artDirection": "editorial_architect",
        "fonts": {"display": "Manrope", "body": "Inter"},
        "colors": {
            "primary": "#005394",
            "primaryContainer": "#2B6CB0",
            "accent": "#F0A020",
            "surface": "#F7FAFC",
            "surfaceContainerLow": "#F1F4F6",
            "surfaceContainerLowest": "#FFFFFF",
            "surfaceContainerHigh": "#E5E9EB",
            "surfaceDim": "#E9EEF2",
            "secondaryContainer": "#D9E7F6",
            "outlineVariant": "#C1C7D2",
            "ink": "#181C1E",
            "muted": "#6F6A73",
            "success": "#E2F6E7",
            "warning": "#FFF0D7",
            "danger": "#FCE4E2",
        },
    },
    "shell": {
        "appName": "RuleMind Experience Studio",
        "tagline": "Decisioning journeys, orchestration, callbacks, and explainability in one mobile studio.",
        "sections": [
            {"id": "home_dashboard", "title": "Home", "icon": "home"},
            {"id": "travel_guard", "title": "Travel Flow", "icon": "flight_takeoff"},
            {"id": "instant_personal_loan", "title": "Loan Flow", "icon": "account_balance"},
            {"id": "sme_underwriting", "title": "SME Flow", "icon": "business"},
            {"id": "scenario_hub", "title": "Scenarios", "icon": "science"},
            {"id": "logs_explainability", "title": "Logs", "icon": "terminal"},
            {"id": "admin_console", "title": "Admin", "icon": "settings_suggest"},
        ],
        "dashboardCards": [
            {
                "id": "travel_guard",
                "title": "Travel Protection",
                "subtitle": "Simple to complex cross-border eligibility, callback verification, and explainability.",
                "badge": "7 steps",
            },
            {
                "id": "instant_personal_loan",
                "title": "Instant Personal Loan",
                "subtitle": "Income, bureau, KYC, fraud overlays, and instant underwriting in Indian lending terms.",
                "badge": "8 steps",
            },
            {
                "id": "sme_underwriting",
                "title": "SME Insurance & Compliance",
                "subtitle": "KYB, census, claims, compliance, routing, and committee review with audit-grade traces.",
                "badge": "10 steps",
            },
        ],
    },
    "logsLanding": {
        "metrics": [
            {"label": "Total flows executed", "value": "128,492", "trend": "+12% vs last week"},
            {"label": "Active rule groups", "value": "84", "trend": "All systems active"},
            {"label": "Callback success", "value": "99.9%", "trend": "2 failures today"},
            {"label": "Decision avg time", "value": "42ms", "trend": "Optimal performance"},
        ]
    },
    "journeys": [
        {
            "id": "travel_guard",
            "title": "Travel Guard",
            "category": "Travel Protection",
            "policyId": "policy_travel_guard",
            "stepCount": 7,
            "primaryColor": "#496FBE",
            "screens": [
                {
                    "id": "travel_landing",
                    "title": "Navigate Global Borders with Absolute Certainty.",
                    "subtitle": "Automated trip eligibility and policy-fit assessment with callback-aware verification.",
                    "type": "landing",
                    "bullets": ["Passport and visa readiness", "Destination risk overlays", "Coverage-fit assessment"],
                },
                {
                    "id": "trip_basics",
                    "title": "Trip & Traveler Basics",
                    "subtitle": "Provide the essential details to tailor Travel Guard protection.",
                    "type": "form",
                    "fields": [
                        _choice_field("destination_country", "Destination Country", ["Japan", "Portugal", "France", "Switzerland", "United Arab Emirates"], required=True),
                        _text_field("destination_city", "City / Region", required=True),
                        _number_field("trip_days", "Trip Duration (Days)", required=True, min_value=1),
                        _choice_field("trip_purpose", "Trip Purpose", ["Leisure", "Business", "Education", "Adventure"], required=True),
                        _number_field("primary_traveller_age", "Primary Traveller Age", required=True, min_value=18),
                        _choice_field("citizenship", "Citizenship", ["India", "United Kingdom", "Canada", "United States"], required=True),
                    ],
                },
                {
                    "id": "travel_readiness",
                    "title": "Travel Readiness",
                    "subtitle": "Ensure your documentation is in order before final eligibility assessment.",
                    "type": "form",
                    "fields": [
                        _choice_field("passport_status", "Passport Availability", ["Currently in possession", "In renewal process", "Not yet applied"], required=True),
                        _number_field("passport_months_valid", "Passport Validity Remaining (Months)", required=True, min_value=0),
                        _choice_field("visa_status", "Visa Status", ["Visa held or not required", "Applied / Pending approval", "Not started"], required=True),
                        _choice_field("medical_flag", "Medical Conditions", ["No material disclosures", "Additional coverage required"], required=True),
                        _choice_field("existing_insurance", "Insurance Purchased?", ["No", "Yes"], required=True),
                    ],
                },
                {
                    "id": "coverage_preferences",
                    "title": "Coverage Preferences",
                    "subtitle": "Customize your coverage for total peace of mind.",
                    "type": "form",
                    "fields": [
                        _number_field("trip_cost_inr", "Total Trip Cost (INR)", required=True, min_value=1000),
                        _choice_field("coverage_tier", "Coverage Tier", ["Standard Protection", "Platinum Shield"], required=True),
                        _choice_field("medical_add_on", "Emergency Medical", ["Included", "Excluded"], required=True),
                        _choice_field("baggage_add_on", "Baggage Protection", ["Included", "Excluded"], required=True),
                    ],
                },
                {
                    "id": "travel_processing",
                    "title": "Verification & Callback Processing",
                    "subtitle": "Aggregating traveler verification, destination support, and policy synthesis callbacks.",
                    "type": "processing",
                },
                {
                    "id": "travel_decision",
                    "title": "Decision Outcome",
                    "subtitle": "Premium eligibility, quote summary, rule log, and callback status.",
                    "type": "outcome",
                },
                {
                    "id": "travel_audit",
                    "title": "Explainability & Audit View",
                    "subtitle": "Decision rationale, callback history, threshold intersections, and action plan guidance.",
                    "type": "audit",
                },
            ],
        },
        {
            "id": "instant_personal_loan",
            "title": "Instant Personal Loan Underwriting",
            "category": "Credit & Loans",
            "policyId": "policy_instant_personal_loan",
            "stepCount": 8,
            "primaryColor": "#32577F",
            "screens": [
                {
                    "id": "loan_landing",
                    "title": "Instant Personal Loan Underwriting.",
                    "subtitle": "A high-fidelity simulation of RuleMind's automated credit assessment journey in India.",
                    "type": "landing",
                    "bullets": ["Bureau screening", "Affordability analysis", "KYC and fraud overlays"],
                },
                {
                    "id": "applicant_basics",
                    "title": "Applicant Basics",
                    "subtitle": "Verify applicant details against regional registries and configure loan terms.",
                    "type": "form",
                    "fields": [
                        _text_field("full_name", "Full Name", required=True),
                        _text_field("mobile_number", "Mobile Number", hint="+91", required=True, keyboard="phone"),
                        _text_field("email", "Email Address", required=True),
                        _text_field("pan", "PAN", required=True),
                        _choice_field("current_city", "Current City", ["Mumbai", "Bengaluru", "New Delhi", "Hyderabad", "Pune"], required=True),
                        _choice_field("employment_type", "Employment Type", ["Salaried", "Self-Employed"], required=True),
                        _number_field("requested_amount_inr", "Requested Loan Amount (INR)", required=True, min_value=10000),
                        _choice_field("requested_tenure_months", "Requested Tenure", ["6", "24", "48", "60"], required=True),
                    ],
                },
                {
                    "id": "income_employment",
                    "title": "Income & Employment Verification",
                    "subtitle": "Assess credit stability and earning potential.",
                    "type": "form",
                    "fields": [
                        _text_field("employer_name", "Employer Name", required=True),
                        _choice_field("employer_type", "Employer Type", ["Private Limited", "Public Sector", "Government", "Multinational"], required=True),
                        _number_field("monthly_income_inr", "Net Monthly Income (INR)", required=True, min_value=10000),
                        _choice_field("salary_credit_mode", "Salary Credit Mode", ["Bank Transfer", "Cheque", "Cash"], required=True),
                        _number_field("work_experience_years", "Total Work Experience (Years)", required=True, min_value=0),
                        _number_field("employer_tenure_months", "Current Employer Tenure (Months)", required=True, min_value=0),
                        _number_field("salary_account_vintage_months", "Salary Account Vintage (Months)", required=True, min_value=0),
                    ],
                },
                {
                    "id": "obligations_stability",
                    "title": "Obligations & Stability",
                    "subtitle": "Define the borrower's debt profile and recurring expenditure.",
                    "type": "form",
                    "fields": [
                        _number_field("existing_emi_inr", "Current EMI Obligations (INR)", required=True, min_value=0),
                        _number_field("active_loans", "Active Loans", required=True, min_value=0),
                        _number_field("fixed_expenses_inr", "Monthly Fixed Expenses (INR)", required=True, min_value=0),
                        _number_field("variable_expenses_inr", "Monthly Variable Expenses (INR)", required=True, min_value=0),
                        _choice_field("residence_type", "Residence Type", ["Self-Owned", "Mortgaged / Financed", "Rented", "Parental / Shared"], required=True),
                        _number_field("housing_cost_inr", "Rent / Mortgage Amount (INR)", required=True, min_value=0),
                    ],
                },
                {
                    "id": "documents_identity",
                    "title": "Documents & Identity Inputs",
                    "subtitle": "Identity, liveness, and income proof capture.",
                    "type": "form",
                    "fields": [
                        _choice_field("income_proof_type", "Income Proof Type", ["Form 16 / ITR V", "Salary Certificate", "Certified P&L"], required=True),
                        _choice_field("utility_bill_verified", "Utility Bill Availability", ["Yes, Verified", "No / Alternative"], required=True),
                        _choice_field("pan_verified", "PAN Verification", ["Authenticated", "Mismatch"], required=True),
                        _number_field("liveness_score", "Liveness Match %", required=True, min_value=0, max_value=100),
                        _choice_field("geo_consistency", "Geo Consistency", ["Matched", "IP mismatch"], required=True),
                    ],
                },
                {
                    "id": "loan_processing",
                    "title": "External Verification & Rule Processing",
                    "subtitle": "Credit bureaus, fraud services, and bank statement parsers in motion.",
                    "type": "processing",
                },
                {
                    "id": "loan_offer",
                    "title": "Offer Decision",
                    "subtitle": "Risk band, approved amount, pricing, and underwriting rationale.",
                    "type": "outcome",
                },
                {
                    "id": "loan_audit",
                    "title": "Underwriting Explainability & Audit",
                    "subtitle": "Conditions, callback evidence, risk drivers, and workflow trace.",
                    "type": "audit",
                },
            ],
        },
        {
            "id": "sme_underwriting",
            "title": "SME Insurance, Compliance & Underwriting Workflow",
            "category": "SME Business",
            "policyId": "policy_sme_underwriting",
            "stepCount": 10,
            "primaryColor": "#294860",
            "screens": [
                {
                    "id": "sme_landing",
                    "title": "SME Insurance, Compliance & Underwriting Workflow",
                    "subtitle": "Automated risk triage from instant quote to committee review using India-ready business inputs.",
                    "type": "landing",
                    "bullets": ["KYB & sanctions", "Census quality", "Claims & compliance routing"],
                },
                {
                    "id": "business_onboarding",
                    "title": "Business Onboarding",
                    "subtitle": "Core registration information as listed on official documents.",
                    "type": "form",
                    "fields": [
                        _text_field("legal_company_name", "Legal Company Name", required=True),
                        _text_field("trade_name", "Trade Name"),
                        _choice_field("incorporation_type", "Incorporation Type", ["Private Limited", "Public Limited", "LLP", "Partnership", "Sole Proprietorship"], required=True),
                        _choice_field("industry_segment", "Industry Segment", ["Software & Technology", "Manufacturing", "Logistics", "Retail & FMCG", "Healthcare"], required=True),
                        _text_field("gstin", "GSTIN", required=True),
                        _text_field("company_pan", "Company PAN", required=True),
                        _number_field("years_in_business", "Years in Business", required=True, min_value=0),
                        _number_field("employee_count", "Employee Count", required=True, min_value=1),
                        _text_field("headquarters_city", "Headquarters City", required=True),
                    ],
                },
                {
                    "id": "coverage_design",
                    "title": "Coverage Design",
                    "subtitle": "Configure sum insured, policy structure, add-ons, and internal underwriting notes.",
                    "type": "form",
                    "fields": [
                        _number_field("sum_insured_inr", "Sum Insured (INR)", required=True, min_value=500000),
                        _choice_field("policy_type", "Policy Type", ["Family Floater", "Individual"], required=True),
                        _choice_field("dependent_inclusion", "Dependent Inclusion", ["Spouse", "Children", "Parents"], multi=True),
                        _choice_field("deductible", "Deductible", ["No Limit", "1% of Sum Insured", "Single Private Room"], required=True),
                        _choice_field("maternity_benefit", "Maternity Benefit", ["Enabled", "Disabled"], required=True),
                        _number_field("estimated_premium_inr", "Estimated Annual Premium (INR)", required=True, min_value=10000),
                    ],
                },
                {
                    "id": "employee_census",
                    "title": "Employee Census Intake",
                    "subtitle": "Participant data collection, validation, and census-quality preview.",
                    "type": "form",
                    "fields": [
                        _number_field("census_record_count", "Total Records", required=True, min_value=1),
                        _number_field("census_validation_errors", "Validation Errors", required=True, min_value=0),
                        _number_field("census_duplicate_hits", "Duplicate Hits", required=True, min_value=0),
                        _number_field("census_quality_score", "Accuracy Score", required=True, min_value=0, max_value=100),
                        _number_field("median_age", "Median Employee Age", required=True, min_value=18),
                    ],
                },
                {
                    "id": "prior_policy_claims",
                    "title": "Prior Policy & Claims Experience",
                    "subtitle": "Historical insurer, claims, exclusions, and loss-ratio profile.",
                    "type": "form",
                    "fields": [
                        _choice_field("policy_type", "Policy Type", ["Renewal", "Fresh"], required=True),
                        _choice_field("existing_insurer", "Existing Insurer", ["ICICI Lombard", "AXA XL", "Allianz", "HDFC ERGO", "Chubb"], required=True),
                        _number_field("claims_count", "Claims Count", required=True, min_value=0),
                        _number_field("loss_ratio_pct", "Loss Ratio %", required=True, min_value=0),
                        _number_field("large_losses", "Large Losses", required=True, min_value=0),
                        _choice_field("claims_disclosed", "Claims Fully Disclosed", ["Yes", "No"], required=True),
                    ],
                },
                {
                    "id": "compliance_documents",
                    "title": "Compliance Documents",
                    "subtitle": "Corporate identity, claims reports, census, and signed declaration readiness.",
                    "type": "form",
                    "fields": [
                        _choice_field("coi_uploaded", "Certificate of Incorporation", ["Uploaded", "Missing"], required=True),
                        _choice_field("pan_uploaded", "Company PAN", ["Uploaded", "Missing"], required=True),
                        _choice_field("claims_report_uploaded", "Claims Report", ["Uploaded", "Missing"], required=True),
                        _choice_field("signed_declaration_uploaded", "Signed Declaration", ["Uploaded", "Missing"], required=True),
                        _choice_field("ubo_docs_ready", "UBO Documentation", ["Ready", "Pending"], required=True),
                    ],
                },
                {
                    "id": "sme_processing",
                    "title": "External Verification & Parsing",
                    "subtitle": "OCR, GST callback, anomaly detection, sanctions screening, and wait-state orchestration.",
                    "type": "processing",
                },
                {
                    "id": "sme_routing",
                    "title": "Underwriting, Compliance & Routing Evaluation",
                    "subtitle": "Support-guideline checks, fraud heuristics, and routing preview.",
                    "type": "processing",
                },
                {
                    "id": "sme_outcome",
                    "title": "Final Outcome",
                    "subtitle": "Instant quote, underwriter review, or compliance hold with conditions and blockers.",
                    "type": "outcome",
                },
                {
                    "id": "sme_audit",
                    "title": "Full Explainability, Audit & Workflow Trace",
                    "subtitle": "Decision blockers, callback evidence, actor trail, and remediation guidance.",
                    "type": "audit",
                },
            ],
        },
    ],
    "admin": {
        "title": "Admin Console",
        "subtitle": "Thresholds, workflow conditions, callback simulators, scenario controls, and full mobile authoring.",
        "tools": [
            {"id": "threshold_controls", "title": "Rule Thresholds", "description": "Adjust sensitive limit parameters and preview decision impact."},
            {"id": "workflow_paths", "title": "Workflow Paths", "description": "Inspect routing branches, review-gate conditions, and fallbacks."},
            {"id": "callback_simulator", "title": "Callback Simulator", "description": "Trigger mock external events and webhook-style updates."},
            {"id": "scenario_controls", "title": "Scenario Controls", "description": "Inject deterministic personas and synthetic edge-case payloads."},
            {"id": "decision_preview", "title": "Decision Preview", "description": "Run dry-run previews before changes are promoted."},
            {"id": "test_harness", "title": "Audit & Test Harness", "description": "Inspect logs, traces, and regression surfaces after edits."},
        ],
        "entities": ADMIN_ENTITY_SCHEMAS,
    },
    "scenarios": [
        {
            "id": "travel_happy_path",
            "journeyId": "travel_guard",
            "title": "Happy Path Traveler",
            "badge": "Low Risk",
            "expectedOutcome": "approve",
            "expectedStatus": "completed",
            "payload": {
                "travel": {
                    "destination_country": "Portugal",
                    "destination_city": "Lisbon",
                    "trip_days": 10,
                    "trip_purpose": "Leisure",
                    "primary_traveller_age": 34,
                    "citizenship": "India",
                    "passport_status": "Currently in possession",
                    "passport_months_valid": 14,
                    "visa_status": "Visa held or not required",
                    "medical_flag": "No material disclosures",
                    "existing_insurance": "No",
                    "trip_cost_inr": 145000,
                    "coverage_tier": "Standard Protection",
                    "medical_add_on": "Included",
                    "baggage_add_on": "Included",
                    "destination_risk": 1,
                    "visa_ready": 1,
                    "support_matrix_ready": 1,
                }
            },
        },
        {
            "id": "travel_senior_review",
            "journeyId": "travel_guard",
            "title": "Senior Traveler Review",
            "badge": "Manual Review",
            "expectedOutcome": "review",
            "expectedStatus": "paused",
            "payload": {
                "travel": {
                    "destination_country": "Japan",
                    "destination_city": "Osaka",
                    "trip_days": 14,
                    "trip_purpose": "Leisure",
                    "primary_traveller_age": 77,
                    "citizenship": "India",
                    "passport_status": "Currently in possession",
                    "passport_months_valid": 11,
                    "visa_status": "Visa held or not required",
                    "medical_flag": "Additional coverage required",
                    "existing_insurance": "Yes",
                    "trip_cost_inr": 220000,
                    "coverage_tier": "Platinum Shield",
                    "medical_add_on": "Included",
                    "baggage_add_on": "Included",
                    "destination_risk": 2,
                    "visa_ready": 1,
                    "support_matrix_ready": 1,
                }
            },
        },
        {
            "id": "travel_passport_failure",
            "journeyId": "travel_guard",
            "title": "Passport Validity Failure",
            "badge": "Critical",
            "expectedOutcome": "reject",
            "expectedStatus": "completed",
            "payload": {
                "travel": {
                    "destination_country": "France",
                    "destination_city": "Paris",
                    "trip_days": 7,
                    "trip_purpose": "Leisure",
                    "primary_traveller_age": 29,
                    "citizenship": "India",
                    "passport_status": "Currently in possession",
                    "passport_months_valid": 2,
                    "visa_status": "Visa held or not required",
                    "medical_flag": "No material disclosures",
                    "existing_insurance": "No",
                    "trip_cost_inr": 98000,
                    "coverage_tier": "Standard Protection",
                    "medical_add_on": "Included",
                    "baggage_add_on": "Included",
                    "destination_risk": 1,
                    "visa_ready": 1,
                    "support_matrix_ready": 1,
                }
            },
        },
        {
            "id": "loan_prime_approved",
            "journeyId": "instant_personal_loan",
            "title": "Prime Borrower Approved",
            "badge": "Happy Path",
            "expectedOutcome": "approve",
            "expectedStatus": "completed",
            "payload": {
                "loan": {
                    "full_name": "Aarav Mehta",
                    "mobile_number": "9876543210",
                    "email": "aarav.mehta@example.in",
                    "pan": "ABCDE1234F",
                    "current_city": "Mumbai",
                    "employment_type": "Salaried",
                    "requested_amount_inr": 850000,
                    "requested_tenure_months": 48,
                    "employer_name": "Axis Advisory Services",
                    "employer_type": "Multinational",
                    "monthly_income_inr": 185000,
                    "salary_credit_mode": "Bank Transfer",
                    "work_experience_years": 9,
                    "employer_tenure_months": 42,
                    "salary_account_vintage_months": 48,
                    "existing_emi_inr": 12000,
                    "active_loans": 1,
                    "fixed_expenses_inr": 18000,
                    "variable_expenses_inr": 22000,
                    "residence_type": "Self-Owned",
                    "housing_cost_inr": 0,
                    "income_proof_type": "Form 16 / ITR V",
                    "utility_bill_verified": "Yes, Verified",
                    "pan_verified": "Authenticated",
                    "liveness_score": 98.4,
                    "geo_consistency": "Matched",
                    "bureau_score": 756,
                    "avg_balance_inr": 124000,
                    "dti_ratio": 0.16,
                }
            },
        },
        {
            "id": "loan_borderline_review",
            "journeyId": "instant_personal_loan",
            "title": "Borderline Borrower",
            "badge": "Review",
            "expectedOutcome": "review",
            "expectedStatus": "paused",
            "payload": {
                "loan": {
                    "full_name": "Rhea Kapoor",
                    "mobile_number": "9898989898",
                    "email": "rhea.kapoor@example.in",
                    "pan": "PQRSK4567L",
                    "current_city": "Pune",
                    "employment_type": "Salaried",
                    "requested_amount_inr": 550000,
                    "requested_tenure_months": 60,
                    "employer_name": "Nextline Retail",
                    "employer_type": "Private Limited",
                    "monthly_income_inr": 72000,
                    "salary_credit_mode": "Bank Transfer",
                    "work_experience_years": 4,
                    "employer_tenure_months": 10,
                    "salary_account_vintage_months": 16,
                    "existing_emi_inr": 14000,
                    "active_loans": 2,
                    "fixed_expenses_inr": 18000,
                    "variable_expenses_inr": 13000,
                    "residence_type": "Rented",
                    "housing_cost_inr": 18000,
                    "income_proof_type": "Salary Certificate",
                    "utility_bill_verified": "Yes, Verified",
                    "pan_verified": "Authenticated",
                    "liveness_score": 95.0,
                    "geo_consistency": "Matched",
                    "bureau_score": 688,
                    "avg_balance_inr": 28000,
                    "dti_ratio": 0.44,
                }
            },
        },
        {
            "id": "loan_high_foir_reject",
            "journeyId": "instant_personal_loan",
            "title": "High FOIR Reject",
            "badge": "Reject",
            "expectedOutcome": "reject",
            "expectedStatus": "completed",
            "payload": {
                "loan": {
                    "full_name": "Kunal Sharma",
                    "mobile_number": "9123456780",
                    "email": "kunal.sharma@example.in",
                    "pan": "ZXCVB9876Q",
                    "current_city": "Hyderabad",
                    "employment_type": "Salaried",
                    "requested_amount_inr": 450000,
                    "requested_tenure_months": 36,
                    "employer_name": "Urban Fleet Labs",
                    "employer_type": "Private Limited",
                    "monthly_income_inr": 58000,
                    "salary_credit_mode": "Bank Transfer",
                    "work_experience_years": 3,
                    "employer_tenure_months": 9,
                    "salary_account_vintage_months": 12,
                    "existing_emi_inr": 24000,
                    "active_loans": 3,
                    "fixed_expenses_inr": 12000,
                    "variable_expenses_inr": 9000,
                    "residence_type": "Rented",
                    "housing_cost_inr": 16000,
                    "income_proof_type": "Form 16 / ITR V",
                    "utility_bill_verified": "Yes, Verified",
                    "pan_verified": "Authenticated",
                    "liveness_score": 97.0,
                    "geo_consistency": "Matched",
                    "bureau_score": 702,
                    "avg_balance_inr": 19000,
                    "dti_ratio": 0.62,
                }
            },
        },
        {
            "id": "loan_fraud_review",
            "journeyId": "instant_personal_loan",
            "title": "Fraud Review Case",
            "badge": "Fraud Overlay",
            "expectedOutcome": "review",
            "expectedStatus": "paused",
            "payload": {
                "loan": {
                    "full_name": "Meera Sethi",
                    "mobile_number": "9988776655",
                    "email": "meera.sethi@example.in",
                    "pan": "LMNOP4321K",
                    "current_city": "Bengaluru",
                    "employment_type": "Salaried",
                    "requested_amount_inr": 980000,
                    "requested_tenure_months": 48,
                    "employer_name": "Cloud Meridian",
                    "employer_type": "Multinational",
                    "monthly_income_inr": 210000,
                    "salary_credit_mode": "Bank Transfer",
                    "work_experience_years": 7,
                    "employer_tenure_months": 30,
                    "salary_account_vintage_months": 32,
                    "existing_emi_inr": 8000,
                    "active_loans": 1,
                    "fixed_expenses_inr": 15000,
                    "variable_expenses_inr": 18000,
                    "residence_type": "Self-Owned",
                    "housing_cost_inr": 0,
                    "income_proof_type": "Form 16 / ITR V",
                    "utility_bill_verified": "Yes, Verified",
                    "pan_verified": "Authenticated",
                    "liveness_score": 96.0,
                    "geo_consistency": "IP mismatch",
                    "bureau_score": 741,
                    "avg_balance_inr": 96000,
                    "dti_ratio": 0.18,
                }
            },
        },
        {
            "id": "loan_kyc_reject",
            "journeyId": "instant_personal_loan",
            "title": "KYC Mismatch Reject",
            "badge": "KYC Mismatch",
            "expectedOutcome": "reject",
            "expectedStatus": "completed",
            "payload": {
                "loan": {
                    "full_name": "Ishita Nair",
                    "mobile_number": "9811122233",
                    "email": "ishita.nair@example.in",
                    "pan": "AAAPA1122P",
                    "current_city": "Mumbai",
                    "employment_type": "Salaried",
                    "requested_amount_inr": 620000,
                    "requested_tenure_months": 24,
                    "employer_name": "Marina Commerce",
                    "employer_type": "Private Limited",
                    "monthly_income_inr": 98000,
                    "salary_credit_mode": "Bank Transfer",
                    "work_experience_years": 5,
                    "employer_tenure_months": 18,
                    "salary_account_vintage_months": 22,
                    "existing_emi_inr": 9000,
                    "active_loans": 1,
                    "fixed_expenses_inr": 14000,
                    "variable_expenses_inr": 16000,
                    "residence_type": "Rented",
                    "housing_cost_inr": 22000,
                    "income_proof_type": "Form 16 / ITR V",
                    "utility_bill_verified": "No / Alternative",
                    "pan_verified": "Mismatch",
                    "liveness_score": 82.0,
                    "geo_consistency": "Matched",
                    "bureau_score": 730,
                    "avg_balance_inr": 48000,
                    "dti_ratio": 0.24,
                }
            },
        },
        {
            "id": "sme_instant_quote",
            "journeyId": "sme_underwriting",
            "title": "Clean SME Instant Quote",
            "badge": "Auto-rate",
            "expectedOutcome": "approve",
            "expectedStatus": "completed",
            "payload": {
                "sme": {
                    "legal_company_name": "Apex Logistics Private Limited",
                    "trade_name": "Apex Logistics",
                    "incorporation_type": "Private Limited",
                    "industry_segment": "Logistics",
                    "gstin": "27AAACA1234F1Z5",
                    "company_pan": "AAACA1234F",
                    "years_in_business": 8,
                    "employee_count": 124,
                    "headquarters_city": "Mumbai",
                    "sum_insured_inr": 10000000,
                    "policy_type": "Family Floater",
                    "dependent_inclusion": ["Spouse", "Children"],
                    "deductible": "1% of Sum Insured",
                    "maternity_benefit": "Enabled",
                    "estimated_premium_inr": 142500,
                    "census_record_count": 1248,
                    "census_validation_errors": 4,
                    "census_duplicate_hits": 1,
                    "census_quality_score": 96.0,
                    "median_age": 34.2,
                    "existing_insurer": "ICICI Lombard",
                    "claims_count": 1,
                    "loss_ratio_pct": 14.5,
                    "large_losses": 0,
                    "claims_disclosed": "Yes",
                    "coi_uploaded": "Uploaded",
                    "pan_uploaded": "Uploaded",
                    "claims_report_uploaded": "Uploaded",
                    "signed_declaration_uploaded": "Uploaded",
                    "ubo_docs_ready": "Ready",
                    "gst_compliance_score": 94,
                    "sanctions_flag": 0,
                    "growth_rate_pct": 18,
                }
            },
        },
        {
            "id": "sme_claims_review",
            "journeyId": "sme_underwriting",
            "title": "High Claims Ratio Review",
            "badge": "Review",
            "expectedOutcome": "review",
            "expectedStatus": "paused",
            "payload": {
                "sme": {
                    "legal_company_name": "Lumina Craft Brewery LLP",
                    "trade_name": "Lumina Craft Brewery",
                    "incorporation_type": "LLP",
                    "industry_segment": "Manufacturing",
                    "gstin": "29AAACL7788P1Z4",
                    "company_pan": "AAACL7788P",
                    "years_in_business": 5,
                    "employee_count": 86,
                    "headquarters_city": "Bengaluru",
                    "sum_insured_inr": 25000000,
                    "policy_type": "Individual",
                    "dependent_inclusion": ["Spouse"],
                    "deductible": "No Limit",
                    "maternity_benefit": "Disabled",
                    "estimated_premium_inr": 268000,
                    "census_record_count": 860,
                    "census_validation_errors": 18,
                    "census_duplicate_hits": 4,
                    "census_quality_score": 88.0,
                    "median_age": 37.0,
                    "existing_insurer": "AXA XL",
                    "claims_count": 12,
                    "loss_ratio_pct": 42.8,
                    "large_losses": 1,
                    "claims_disclosed": "Yes",
                    "coi_uploaded": "Uploaded",
                    "pan_uploaded": "Uploaded",
                    "claims_report_uploaded": "Uploaded",
                    "signed_declaration_uploaded": "Uploaded",
                    "ubo_docs_ready": "Ready",
                    "gst_compliance_score": 86,
                    "sanctions_flag": 0,
                    "growth_rate_pct": 72,
                }
            },
        },
        {
            "id": "sme_census_failure",
            "journeyId": "sme_underwriting",
            "title": "Census Quality Failure",
            "badge": "Clarification",
            "expectedOutcome": "review",
            "expectedStatus": "paused",
            "payload": {
                "sme": {
                    "legal_company_name": "Northwind Health Services LLP",
                    "trade_name": "Northwind Health",
                    "incorporation_type": "LLP",
                    "industry_segment": "Healthcare",
                    "gstin": "07AAACN3322D1Z7",
                    "company_pan": "AAACN3322D",
                    "years_in_business": 6,
                    "employee_count": 220,
                    "headquarters_city": "New Delhi",
                    "sum_insured_inr": 18000000,
                    "policy_type": "Family Floater",
                    "dependent_inclusion": ["Spouse", "Children", "Parents"],
                    "deductible": "1% of Sum Insured",
                    "maternity_benefit": "Enabled",
                    "estimated_premium_inr": 312000,
                    "census_record_count": 1180,
                    "census_validation_errors": 114,
                    "census_duplicate_hits": 26,
                    "census_quality_score": 72.0,
                    "median_age": 38.5,
                    "existing_insurer": "HDFC ERGO",
                    "claims_count": 4,
                    "loss_ratio_pct": 26.0,
                    "large_losses": 0,
                    "claims_disclosed": "Yes",
                    "coi_uploaded": "Uploaded",
                    "pan_uploaded": "Uploaded",
                    "claims_report_uploaded": "Uploaded",
                    "signed_declaration_uploaded": "Uploaded",
                    "ubo_docs_ready": "Ready",
                    "gst_compliance_score": 90,
                    "sanctions_flag": 0,
                    "growth_rate_pct": 21,
                }
            },
        },
        {
            "id": "sme_compliance_hold",
            "journeyId": "sme_underwriting",
            "title": "Compliance Hold",
            "badge": "PEP Match Alert",
            "expectedOutcome": "review",
            "expectedStatus": "paused",
            "payload": {
                "sme": {
                    "legal_company_name": "Global Tech Solutions Private Limited",
                    "trade_name": "Global Tech Solutions",
                    "incorporation_type": "Private Limited",
                    "industry_segment": "Software & Technology",
                    "gstin": "27AAACG5555Q1Z3",
                    "company_pan": "AAACG5555Q",
                    "years_in_business": 4,
                    "employee_count": 64,
                    "headquarters_city": "Pune",
                    "sum_insured_inr": 12500000,
                    "policy_type": "Individual",
                    "dependent_inclusion": ["Spouse"],
                    "deductible": "No Limit",
                    "maternity_benefit": "Enabled",
                    "estimated_premium_inr": 198000,
                    "census_record_count": 642,
                    "census_validation_errors": 8,
                    "census_duplicate_hits": 1,
                    "census_quality_score": 94.0,
                    "median_age": 31.8,
                    "existing_insurer": "ICICI Lombard",
                    "claims_count": 1,
                    "loss_ratio_pct": 12.0,
                    "large_losses": 0,
                    "claims_disclosed": "Yes",
                    "coi_uploaded": "Uploaded",
                    "pan_uploaded": "Uploaded",
                    "claims_report_uploaded": "Uploaded",
                    "signed_declaration_uploaded": "Uploaded",
                    "ubo_docs_ready": "Pending",
                    "gst_compliance_score": 91,
                    "sanctions_flag": 1,
                    "growth_rate_pct": 420,
                }
            },
        },
    ],
}


def build_experience_manifest(tenant_id: str, api_base_url: str, latest_bundle_version: int = 0) -> Dict[str, Any]:
    manifest = copy.deepcopy(EXPERIENCE_MANIFEST_TEMPLATE)
    manifest["tenantId"] = tenant_id
    manifest["apiBaseUrl"] = api_base_url.rstrip("/")
    manifest["latestBundleVersion"] = latest_bundle_version
    return manifest
