from copy import deepcopy


CONNECTORS = [
    {
        "id": "bureau",
        "name": "Credit Bureau",
        "icon": "bureau",
        "color": "#4d8eff",
        "description": "CIBIL / Experian",
        "schema_paths": [
            "scores[].scoreName",
            "scores[].score",
            "scores[].scoreCardName",
            "scores[].reasonCodes[].reasonCodeValue",
            "accounts[].accountType",
            "accounts[].currentBalance",
            "accounts[].highCreditAmount",
            "accounts[].creditLimit",
            "accounts[].cashLimit",
            "accounts[].dateOpened",
            "accounts[].dateClosed",
            "accounts[].dateReported",
            "accounts[].paymentHistory",
            "accounts[].emiAmount",
            "accounts[].ownershipIndicator",
            "accounts[].paymentTenure",
            "accounts[].interestRate",
            "accounts[].collateralType",
            "accounts[].actualPaymentAmount",
            "accounts[].lastPaymentDate",
            "accounts[].paymentFrequency",
            "enquiries[].enquiryDate",
            "enquiries[].enquiryPurpose",
            "enquiries[].enquiryAmount",
            "names[].name",
            "names[].birthDate",
            "names[].gender",
            "ids[].idType",
            "ids[].idNumber",
            "addresses[].pinCode",
            "addresses[].stateCode",
            "telephones[].telephoneNumber",
            "employment[].occupationCode",
        ],
        "sample_payload": {
            "scores": [
                {"scoreName": "CIBILTUSC3", "score": "00741", "scoreCardName": "08", "scoreCardVersion": "10", "scoreDate": "25022026",
                 "reasonCodes": [{"reasonCodeName": "reasonCode1", "reasonCodeValue": "35"}, {"reasonCodeName": "reasonCode2", "reasonCodeValue": "39"}]},
                {"scoreName": "PLSCORE", "score": "00791", "scoreCardName": "02", "scoreCardVersion": "10", "scoreDate": "25022026",
                 "reasonCodes": [{"reasonCodeName": "reasonCode1", "reasonCodeValue": "13"}]},
            ],
            "accounts": [
                {"accountType": "05", "currentBalance": 87047, "highCreditAmount": 88652, "dateOpened": "29122025", "dateReported": "15022026",
                 "emiAmount": 3656, "interestRate": 27.76, "paymentHistory": "000000000", "ownershipIndicator": 1, "paymentTenure": 36, "index": "T002"},
                {"accountType": "10", "currentBalance": 9288, "highCreditAmount": 10989, "creditLimit": 10000, "cashLimit": 2000,
                 "dateOpened": "24122022", "dateReported": "15022026", "paymentHistory": "000000000000000000000000000000000000000023003000000000000000000000000000000003000000000XXX000000000000000000",
                 "ownershipIndicator": 1, "index": "T033"},
                {"accountType": "10", "currentBalance": 67193, "highCreditAmount": 83770, "creditLimit": 64000, "cashLimit": 3456,
                 "dateOpened": "15092022", "dateReported": "15022026", "interestRate": 46.2, "paymentHistory": "000000000000000000000000000000000000000000000000000000000000XXX000000000000000000000000000000000000000000000",
                 "ownershipIndicator": 1, "index": "T037"},
                {"accountType": "01", "currentBalance": 40650, "highCreditAmount": 62000, "collateralType": "00",
                 "dateOpened": "30062025", "dateReported": "15022026", "emiAmount": 2995, "paymentHistory": "000000000000000000000000000",
                 "ownershipIndicator": 1, "paymentTenure": 24, "index": "T006"},
                {"accountType": "07", "currentBalance": 0, "highCreditAmount": 200000, "dateClosed": "31012025",
                 "dateOpened": "31012025", "dateReported": "31012025", "paymentHistory": "STD",
                 "ownershipIndicator": 1, "paymentTenure": 12, "index": "T009"},
                {"accountType": "05", "currentBalance": 0, "highCreditAmount": 598209, "dateClosed": "13022025",
                 "dateOpened": "11112023", "dateReported": "30042025", "paymentHistory": "000000000000000000000000000000000000000000000000000000",
                 "ownershipIndicator": 1, "index": "T020"},
            ],
            "enquiries": [
                {"enquiryAmount": 4000, "enquiryDate": "01022026", "enquiryPurpose": "05", "index": "I001"},
                {"enquiryAmount": 100, "enquiryDate": "06012026", "enquiryPurpose": "51", "index": "I002"},
                {"enquiryAmount": 4000, "enquiryDate": "28122025", "enquiryPurpose": "05", "index": "I003"},
                {"enquiryAmount": 100000, "enquiryDate": "19122025", "enquiryPurpose": "05", "index": "I004"},
                {"enquiryAmount": 500000, "enquiryDate": "05062025", "enquiryPurpose": "05", "index": "I017"},
            ],
            "names": [{"birthDate": "07081978", "gender": "2", "index": "N01", "name": "THANISERIL HAMEED NISHAD"}],
            "ids": [
                {"idNumber": "AUVPN6738R", "idType": "01", "index": "I01"},
                {"idNumber": "GJK1145283", "idType": "03", "index": "I02"},
            ],
            "addresses": [{"addressCategory": "02", "dateReported": "31082024", "line1": "II387KARIMUKAL ERNAKULAM 682303", "pinCode": "682303", "stateCode": "32", "index": "A01"}],
            "telephones": [{"telephoneNumber": "9037532477", "telephoneType": "01", "index": "T01"}],
            "employment": [{"accountType": "45", "dateReported": "15022026", "occupationCode": "03", "index": "E01"}],
        },
        "is_active": True,
        "config": {"auth_type": "api_key", "base_url": "https://bureau.example.com/pull", "timeout_ms": 3000, "retries": 2},
    },
    {
        "id": "bank",
        "name": "Bank Statement",
        "icon": "bank",
        "color": "#10b981",
        "description": "Perfios / Finbox",
        "schema_paths": [
            "summary.avgBalance",
            "salary[].amount",
            "bounces[].amount",
            "emiPayments[].amount",
        ],
        "sample_payload": {
            "summary": {"avgBalance": 45200},
            "salary": [{"amount": 62000}],
            "bounces": [{"amount": 5000}],
            "emiPayments": [{"amount": 8500}],
        },
        "is_active": True,
        "config": {"auth_type": "bearer", "base_url": "https://bank.example.com/statements", "timeout_ms": 3000, "retries": 2},
    },
    {
        "id": "gst",
        "name": "GST Returns",
        "icon": "gst",
        "color": "#f5a623",
        "description": "Business filing data",
        "schema_paths": ["annualTurnover", "complianceScore", "filingStatus"],
        "sample_payload": {"annualTurnover": 4800000, "complianceScore": 92, "filingStatus": "ACTIVE"},
        "is_active": True,
        "config": {"auth_type": "oauth2", "base_url": "https://gst.example.com/returns", "timeout_ms": 3000, "retries": 2},
    },
    {
        "id": "device",
        "name": "Device / App",
        "icon": "device",
        "color": "#a78bfa",
        "description": "SDK signals",
        "schema_paths": ["lendingAppsCount", "vpnDetected", "rootDetected", "deviceAge"],
        "sample_payload": {"lendingAppsCount": 2, "vpnDetected": False, "rootDetected": False, "deviceAge": 410},
        "is_active": True,
        "config": {"auth_type": "signed_webhook", "webhook_url": "https://example.com/rulemind/device", "timeout_ms": 3000, "retries": 2},
    },
    {
        "id": "kyc",
        "name": "KYC / Identity",
        "icon": "kyc",
        "color": "#f06060",
        "description": "PAN, Aadhaar match",
        "schema_paths": ["nameMatchScore", "age", "panValid"],
        "sample_payload": {"nameMatchScore": 95, "age": 28, "panValid": True},
        "is_active": True,
        "config": {"auth_type": "basic", "base_url": "https://kyc.example.com/verify", "timeout_ms": 3000, "retries": 2},
    },
    {
        "id": "custom",
        "name": "Custom API",
        "icon": "custom",
        "color": "#64748b",
        "description": "Any JSON",
        "schema_paths": ["(user-defined)"],
        "sample_payload": {},
        "is_active": False,
        "config": {"schema_editor_enabled": True},
    },
]


VARIABLES = [
    {
        "id": "bureau_score",
        "name": "Bureau Score",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "CIBIL score",
        "code": "@variable(source=\"bureau\")\ndef bureau_score(payload, variables, apis):\n    for score in payload.get(\"scores\", []):\n        if score.get(\"scoreName\") == \"CIBILTUSC3\":\n            return int(score.get(\"score\", 0))\n    return 0\n",
        "status": "prod",
        "seed_value": 760,
    },
    {
        "id": "active_accounts",
        "name": "Active Accounts",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Open accounts",
        "code": "@variable(source=\"bureau\")\ndef active_accounts(payload, variables, apis):\n    return sum(1 for account in payload.get(\"accounts\", []) if not account.get(\"dateClosed\"))\n",
        "status": "prod",
        "seed_value": 4,
    },
    {
        "id": "credit_util",
        "name": "Credit Util %",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "CC balance / limit",
        "code": "@variable(source=\"bureau\")\ndef credit_util(payload, variables, apis):\n    cards = [account for account in payload.get(\"accounts\", []) if account.get(\"accountType\") == \"10\"]\n    limit_total = sum(account.get(\"creditLimit\", 0) for account in cards)\n    balance_total = sum(account.get(\"currentBalance\", 0) for account in cards)\n    return round((balance_total / limit_total) * 100, 1) if limit_total else 0\n",
        "status": "prod",
        "seed_value": 5.2,
    },
    {
        "id": "dpd_count",
        "name": "DPD 30+",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Past due count",
        "code": "@variable(source=\"bureau\")\ndef dpd_count(payload, variables, apis):\n    count = 0\n    for account in payload.get(\"accounts\", []):\n        history = account.get(\"paymentHistory\", \"\")\n        for index in range(0, len(history), 3):\n            chunk = history[index:index + 3]\n            if chunk.isdigit() and int(chunk) >= 30:\n                count += 1\n    return count\n",
        "status": "prod",
        "seed_value": 0,
    },
    {
        "id": "enquiry_6m",
        "name": "Enquiries 6M",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Hard pulls in last 6 months from API request date",
        "code": "@variable(source=\"bureau\")\ndef enquiry_6m(payload, variables, apis):\n    from datetime import datetime\n    now = datetime.now()\n    count = 0\n    for e in payload.get(\"enquiries\", []):\n        raw = e.get(\"enquiryDate\", \"\")\n        if len(raw) == 8 and raw.isdigit():\n            dt = datetime(int(raw[4:8]), int(raw[2:4]), int(raw[0:2]))\n            if 0 <= (now - dt).days <= 180:\n                count += 1\n    return count\n",
        "status": "prod",
        "seed_value": 12,
    },
    {
        "id": "total_outstanding",
        "name": "Total Outstanding",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Sum of current balance across all accounts",
        "code": "@variable(source=\"bureau\")\ndef total_outstanding(payload, variables, apis):\n    return sum(a.get(\"currentBalance\", 0) for a in payload.get(\"accounts\", []))\n",
        "status": "dev",
        "seed_value": 1376598,
    },
    {
        "id": "total_sanctioned",
        "name": "Total Sanctioned",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Sum of highCreditAmount across all accounts",
        "code": "@variable(source=\"bureau\")\ndef total_sanctioned(payload, variables, apis):\n    return sum(a.get(\"highCreditAmount\", 0) for a in payload.get(\"accounts\", []))\n",
        "status": "dev",
        "seed_value": 7465537,
    },
    {
        "id": "secured_loan_count",
        "name": "Secured Loan Count",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Active secured loans (auto, housing, property)",
        "code": "@variable(source=\"bureau\")\ndef secured_loan_count(payload, variables, apis):\n    secured_types = {\"01\", \"02\", \"03\", \"12\", \"13\"}\n    return sum(1 for a in payload.get(\"accounts\", []) if a.get(\"accountType\") in secured_types and not a.get(\"dateClosed\"))\n",
        "status": "dev",
        "seed_value": 4,
    },
    {
        "id": "unsecured_loan_count",
        "name": "Unsecured Loan Count",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Active unsecured loans (PL, CL, CC, gold, BNPL)",
        "code": "@variable(source=\"bureau\")\ndef unsecured_loan_count(payload, variables, apis):\n    unsecured_types = {\"05\", \"06\", \"07\", \"10\", \"35\", \"36\", \"45\", \"69\"}\n    return sum(1 for a in payload.get(\"accounts\", []) if a.get(\"accountType\") in unsecured_types and not a.get(\"dateClosed\"))\n",
        "status": "dev",
        "seed_value": 14,
    },
    {
        "id": "total_emi",
        "name": "Total EMI",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Sum of EMI amounts on active accounts",
        "code": "@variable(source=\"bureau\")\ndef total_emi(payload, variables, apis):\n    return sum(a.get(\"emiAmount\", 0) for a in payload.get(\"accounts\", []) if not a.get(\"dateClosed\"))\n",
        "status": "dev",
        "seed_value": 232605,
    },
    {
        "id": "closed_accounts",
        "name": "Closed Accounts",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Count of closed/settled accounts",
        "code": "@variable(source=\"bureau\")\ndef closed_accounts(payload, variables, apis):\n    return sum(1 for a in payload.get(\"accounts\", []) if a.get(\"dateClosed\"))\n",
        "status": "dev",
        "seed_value": 29,
    },
    {
        "id": "max_dpd",
        "name": "Max DPD",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Worst delinquency across all accounts. XXX treated as 90",
        "code": "@variable(source=\"bureau\")\ndef max_dpd(payload, variables, apis):\n    worst = 0\n    for a in payload.get(\"accounts\", []):\n        history = a.get(\"paymentHistory\", \"\")\n        for i in range(0, len(history), 3):\n            chunk = history[i:i+3]\n            if chunk.isdigit():\n                worst = max(worst, int(chunk))\n            elif chunk in (\"XXX\", \"xxx\"):\n                worst = max(worst, 90)\n    return worst\n",
        "status": "dev",
        "seed_value": 90,
    },
    {
        "id": "active_credit_cards",
        "name": "Active Credit Cards",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Count of active credit card accounts (type 10)",
        "code": "@variable(source=\"bureau\")\ndef active_credit_cards(payload, variables, apis):\n    return sum(1 for a in payload.get(\"accounts\", []) if a.get(\"accountType\") == \"10\" and not a.get(\"dateClosed\"))\n",
        "status": "dev",
        "seed_value": 4,
    },
    {
        "id": "total_cc_limit",
        "name": "Total CC Limit",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Total credit limit across active credit cards",
        "code": "@variable(source=\"bureau\")\ndef total_cc_limit(payload, variables, apis):\n    return sum(a.get(\"creditLimit\", 0) for a in payload.get(\"accounts\", []) if a.get(\"accountType\") == \"10\" and not a.get(\"dateClosed\"))\n",
        "status": "dev",
        "seed_value": 128000,
    },
    {
        "id": "credit_age_months",
        "name": "Credit Age Months",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Months since oldest account opened (credit history length)",
        "code": "@variable(source=\"bureau\")\ndef credit_age_months(payload, variables, apis):\n    from datetime import datetime\n    oldest = None\n    for a in payload.get(\"accounts\", []):\n        raw = a.get(\"dateOpened\", \"\")\n        if len(raw) == 8 and raw.isdigit():\n            dt = datetime(int(raw[4:8]), int(raw[2:4]), int(raw[0:2]))\n            if oldest is None or dt < oldest:\n                oldest = dt\n    if oldest:\n        now = datetime.now()\n        return (now.year - oldest.year) * 12 + (now.month - oldest.month)\n    return 0\n",
        "status": "dev",
        "seed_value": 257,
    },
    {
        "id": "writeoff_flag",
        "name": "Writeoff Flag",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "1 if any active account has XXX (writeoff) in payment history",
        "code": "@variable(source=\"bureau\")\ndef writeoff_flag(payload, variables, apis):\n    for a in payload.get(\"accounts\", []):\n        if not a.get(\"dateClosed\") and \"XXX\" in a.get(\"paymentHistory\", \"\"):\n            return 1\n    return 0\n",
        "status": "dev",
        "seed_value": 1,
    },
    {
        "id": "enquiry_30d",
        "name": "Enquiries 30D",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Enquiry count in last 30 days from API request date",
        "code": "@variable(source=\"bureau\")\ndef enquiry_30d(payload, variables, apis):\n    from datetime import datetime\n    now = datetime.now()\n    count = 0\n    for e in payload.get(\"enquiries\", []):\n        raw = e.get(\"enquiryDate\", \"\")\n        if len(raw) == 8 and raw.isdigit():\n            dt = datetime(int(raw[4:8]), int(raw[2:4]), int(raw[0:2]))\n            diff_days = (now - dt).days\n            if 0 <= diff_days <= 30:\n                count += 1\n    return count\n",
        "status": "dev",
        "seed_value": 0,
    },
    {
        "id": "enquiry_3m",
        "name": "Enquiries 3M",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Enquiry count in last 3 months from API request date",
        "code": "@variable(source=\"bureau\")\ndef enquiry_3m(payload, variables, apis):\n    from datetime import datetime\n    now = datetime.now()\n    count = 0\n    for e in payload.get(\"enquiries\", []):\n        raw = e.get(\"enquiryDate\", \"\")\n        if len(raw) == 8 and raw.isdigit():\n            dt = datetime(int(raw[4:8]), int(raw[2:4]), int(raw[0:2]))\n            if 0 <= (now - dt).days <= 90:\n                count += 1\n    return count\n",
        "status": "dev",
        "seed_value": 3,
    },
    {
        "id": "overdue_accounts",
        "name": "Overdue Accounts",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Active accounts with any delinquency (DPD>0 or XXX)",
        "code": "@variable(source=\"bureau\")\ndef overdue_accounts(payload, variables, apis):\n    count = 0\n    for a in payload.get(\"accounts\", []):\n        if a.get(\"dateClosed\"):\n            continue\n        history = a.get(\"paymentHistory\", \"\")\n        for i in range(0, len(history), 3):\n            chunk = history[i:i+3]\n            if chunk in (\"XXX\", \"xxx\"):\n                count += 1\n                break\n            if chunk.isdigit() and int(chunk) > 0:\n                count += 1\n                break\n    return count\n",
        "status": "dev",
        "seed_value": 2,
    },
    {
        "id": "avg_interest_rate",
        "name": "Avg Interest Rate",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Average interest rate on active accounts that report it",
        "code": "@variable(source=\"bureau\")\ndef avg_interest_rate(payload, variables, apis):\n    rates = [a[\"interestRate\"] for a in payload.get(\"accounts\", []) if not a.get(\"dateClosed\") and \"interestRate\" in a]\n    return round(sum(rates) / len(rates), 2) if rates else 0\n",
        "status": "dev",
        "seed_value": 22.47,
    },
    {
        "id": "outstanding_ratio",
        "name": "Outstanding Ratio %",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Current outstanding as % of total sanctioned (active accounts)",
        "code": "@variable(source=\"bureau\")\ndef outstanding_ratio(payload, variables, apis):\n    active = [a for a in payload.get(\"accounts\", []) if not a.get(\"dateClosed\")]\n    sanctioned = sum(a.get(\"highCreditAmount\", 0) for a in active)\n    outstanding = sum(a.get(\"currentBalance\", 0) for a in active)\n    return round((outstanding / sanctioned) * 100, 1) if sanctioned else 0\n",
        "status": "dev",
        "seed_value": 50.3,
    },
    {
        "id": "newest_account_age",
        "name": "Newest Account Age",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Months since newest account opened",
        "code": "@variable(source=\"bureau\")\ndef newest_account_age(payload, variables, apis):\n    from datetime import datetime\n    newest = None\n    for a in payload.get(\"accounts\", []):\n        raw = a.get(\"dateOpened\", \"\")\n        if len(raw) == 8 and raw.isdigit():\n            dt = datetime(int(raw[4:8]), int(raw[2:4]), int(raw[0:2]))\n            if newest is None or dt > newest:\n                newest = dt\n    if newest:\n        now = datetime.now()\n        return (now.year - newest.year) * 12 + (now.month - newest.month)\n    return 0\n",
        "status": "dev",
        "seed_value": 2,
    },
    {
        "id": "pl_score",
        "name": "PL Score",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Personal Loan score (PLSCORE) from bureau",
        "code": "@variable(source=\"bureau\")\ndef pl_score(payload, variables, apis):\n    for score in payload.get(\"scores\", []):\n        if score.get(\"scoreName\") == \"PLSCORE\":\n            return int(score.get(\"score\", 0))\n    return 0\n",
        "status": "dev",
        "seed_value": 791,
    },
    {
        "id": "active_gold_loans",
        "name": "Active Gold Loans",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Count of active gold loan accounts (type 07)",
        "code": "@variable(source=\"bureau\")\ndef active_gold_loans(payload, variables, apis):\n    return sum(1 for a in payload.get(\"accounts\", []) if a.get(\"accountType\") == \"07\" and not a.get(\"dateClosed\"))\n",
        "status": "dev",
        "seed_value": 2,
    },
    {
        "id": "applicant_age",
        "name": "Applicant Age",
        "category": "Bureau",
        "source_id": "bureau",
        "description": "Age calculated from date of birth in bureau names section",
        "code": "@variable(source=\"bureau\")\ndef applicant_age(payload, variables, apis):\n    from datetime import datetime\n    names = payload.get(\"names\", [])\n    if not names:\n        return 0\n    dob_raw = names[0].get(\"birthDate\", \"\")\n    if len(dob_raw) == 8 and dob_raw.isdigit():\n        dob = datetime(int(dob_raw[4:8]), int(dob_raw[2:4]), int(dob_raw[0:2]))\n        now = datetime.now()\n        age = now.year - dob.year\n        if (now.month, now.day) < (dob.month, dob.day):\n            age -= 1\n        return age\n    return 0\n",
        "status": "dev",
        "seed_value": 47,
    },
    {
        "id": "avg_balance",
        "name": "Avg Balance",
        "category": "Banking",
        "source_id": "bank",
        "description": "Monthly average balance",
        "code": "@variable(source=\"bank\")\ndef avg_balance(payload, variables, apis):\n    return payload.get(\"summary\", {}).get(\"avgBalance\", 0)\n",
        "status": "uat",
        "seed_value": 45200,
    },
    {
        "id": "salary",
        "name": "Latest Salary",
        "category": "Banking",
        "source_id": "bank",
        "description": "Salary credit",
        "code": "@variable(source=\"bank\")\ndef salary(payload, variables, apis):\n    salaries = payload.get(\"salary\", [])\n    return salaries[0].get(\"amount\", 0) if salaries else 0\n",
        "status": "uat",
        "seed_value": 62000,
    },
    {
        "id": "bounces",
        "name": "Bounce Count",
        "category": "Banking",
        "source_id": "bank",
        "description": "Cheque bounces",
        "code": "@variable(source=\"bank\")\ndef bounces(payload, variables, apis):\n    return len(payload.get(\"bounces\", []))\n",
        "status": "uat",
        "seed_value": 1,
    },
    {
        "id": "foir",
        "name": "FOIR %",
        "category": "Banking",
        "source_id": "bank",
        "description": "Obligations / income",
        "code": "@variable(source=\"bank\")\ndef foir(payload, variables, apis):\n    salaries = payload.get(\"salary\", [])\n    income = salaries[0].get(\"amount\", 0) if salaries else 0\n    obligations = sum(item.get(\"amount\", 0) for item in payload.get(\"emiPayments\", []))\n    return round((obligations / income) * 100, 1) if income else 0\n",
        "status": "uat",
        "seed_value": 13.7,
    },
    {
        "id": "gst_turnover",
        "name": "Turnover",
        "category": "Business",
        "source_id": "gst",
        "description": "Annual turnover",
        "code": "@variable(source=\"gst\")\ndef gst_turnover(payload, variables, apis):\n    return payload.get(\"annualTurnover\", 0)\n",
        "status": "dev",
        "seed_value": 4800000,
    },
    {
        "id": "gst_compliance",
        "name": "GST Compliance",
        "category": "Business",
        "source_id": "gst",
        "description": "Filing score",
        "code": "@variable(source=\"gst\")\ndef gst_compliance(payload, variables, apis):\n    return payload.get(\"complianceScore\", 0)\n",
        "status": "dev",
        "seed_value": 92,
    },
    {
        "id": "lending_apps",
        "name": "Lending Apps",
        "category": "Device",
        "source_id": "device",
        "description": "App count",
        "code": "@variable(source=\"device\")\ndef lending_apps(payload, variables, apis):\n    return payload.get(\"lendingAppsCount\", 0)\n",
        "status": "dev",
        "seed_value": 2,
    },
    {
        "id": "device_risk",
        "name": "Device Risk",
        "category": "Device",
        "source_id": "device",
        "description": "VPN / root flag",
        "code": "@variable(source=\"device\")\ndef device_risk(payload, variables, apis):\n    return 1 if payload.get(\"vpnDetected\") or payload.get(\"rootDetected\") else 0\n",
        "status": "dev",
        "seed_value": 0,
    },
    {
        "id": "name_match",
        "name": "Name Match",
        "category": "Identity",
        "source_id": "kyc",
        "description": "KYC score",
        "code": "@variable(source=\"kyc\")\ndef name_match(payload, variables, apis):\n    return payload.get(\"nameMatchScore\", 0)\n",
        "status": "dev",
        "seed_value": 95,
    },
    {
        "id": "age",
        "name": "Age",
        "category": "Identity",
        "source_id": "kyc",
        "description": "Applicant age",
        "code": "@variable(source=\"kyc\")\ndef age(payload, variables, apis):\n    return payload.get(\"age\", 0)\n",
        "status": "dev",
        "seed_value": 28,
    },
]


RULES = [
    {
        "id": "r1",
        "name": "PL Score Gate (Bureau+Bank+KYC)",
        "status": "prod",
        "nodes": [
            {"id": "n1", "type": "condition", "variable": "bureau_score", "operator": ">=", "value": "700", "label": "Condition"},
            {"id": "n2", "type": "and", "label": "AND"},
            {"id": "n3", "type": "condition", "variable": "avg_balance", "operator": ">=", "value": "20000", "label": "Condition"},
            {"id": "n4", "type": "and", "label": "AND"},
            {"id": "n5", "type": "condition", "variable": "age", "operator": ">=", "value": "21", "label": "Condition"},
            {"id": "n6", "type": "approve", "label": "Approve"},
        ],
    },
    {
        "id": "r2",
        "name": "Risk Block (Bureau+Bank+Device)",
        "status": "uat",
        "nodes": [
            {"id": "n1", "type": "condition", "variable": "dpd_count", "operator": ">", "value": "0", "label": "Condition"},
            {"id": "n2", "type": "or", "label": "OR"},
            {"id": "n3", "type": "condition", "variable": "bounces", "operator": ">", "value": "2", "label": "Condition"},
            {"id": "n4", "type": "or", "label": "OR"},
            {"id": "n5", "type": "condition", "variable": "device_risk", "operator": "==", "value": "1", "label": "Condition"},
            {"id": "n6", "type": "reject", "label": "Reject"},
        ],
    },
]


SCORECARDS = [
    {
        "id": "sc1",
        "name": "PL Eligibility Score",
        "base_score": 300,
        "max_score": 900,
        "status": "prod",
        "bins": [
            {
                "variable_id": "bureau_score",
                "ranges": [
                    {"min": 0, "max": 649, "points": -80},
                    {"min": 650, "max": 719, "points": 0},
                    {"min": 720, "max": 780, "points": 40},
                    {"min": 781, "max": 900, "points": 80},
                ],
            },
            {
                "variable_id": "avg_balance",
                "ranges": [
                    {"min": 0, "max": 10000, "points": -30},
                    {"min": 10001, "max": 30000, "points": 10},
                    {"min": 30001, "max": 999999999, "points": 40},
                ],
            },
            {
                "variable_id": "bounces",
                "ranges": [
                    {"min": 0, "max": 0, "points": 30},
                    {"min": 1, "max": 2, "points": -10},
                    {"min": 3, "max": 999, "points": -50},
                ],
            },
        ],
    }
]


POLICIES = [
    {
        "id": "policy_pl_underwriting",
        "name": "PL Underwriting",
        "status": "uat",
        "steps": [
            {"id": "step_1", "type": "connector", "ref_id": "bureau", "label": "Bureau Pull"},
            {"id": "step_2", "type": "connector", "ref_id": "bank", "label": "Bank Analysis"},
            {"id": "step_3", "type": "connector", "ref_id": "kyc", "label": "KYC Check"},
            {"id": "step_4", "type": "rule", "ref_id": "r1", "label": "Score Gate"},
            {"id": "step_5", "type": "scorecard", "ref_id": "sc1", "label": "PL Scorecard"},
            {"id": "step_6", "type": "rule", "ref_id": "r2", "label": "Risk Block"},
            {"id": "step_7", "type": "outcome", "ref_id": "approve", "label": "Decision"},
        ],
    }
]


DEFAULT_SETTINGS = {
    "api_base_url": "http://localhost:8080",
    "auth_config": {"method": "bearer", "token": ""},
    "engine_config": {"python_version": "3.11", "timeout_ms": 2000, "memory_mb": 128},
    "source_defaults": {"default_format": "json", "batch_support": True, "active_sources": ["bureau", "bank", "gst", "device", "kyc"]},
    "audit_retention_days": 90,
    "theme_mode": "light",
}


def connector_map():
    return {item["id"]: deepcopy(item) for item in CONNECTORS}


def variable_templates():
    return deepcopy(VARIABLES)
