apiVersion: apps/v1
kind: Deployment
metadata:
  name: rulemind-web
spec:
  replicas: {{ .Values.replicaCount.web }}
  selector:
    matchLabels:
      app: rulemind-web
  template:
    metadata:
      labels:
        app: rulemind-web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "http://rulemind-api:8080"
          resources:
{{ toYaml .Values.resources.web | indent 12 }}
