apiVersion: apps/v1
kind: Deployment
metadata:
  name: rulemind-api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app: rulemind-api
  template:
    metadata:
      labels:
        app: rulemind-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: rulemind-config
            - secretRef:
                name: rulemind-secrets
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          resources:
{{ toYaml .Values.resources.api | indent 12 }}
