apiVersion: v1
kind: Secret
metadata:
  name: rulemind-secrets
type: Opaque
stringData:
  RULEMIND_CONFIG_KEY: {{ .Values.env.configKey | quote }}
  RULEMIND_ADMIN_JWT_SECRET: {{ .Values.env.adminJwtSecret | quote }}
