apiVersion: v1
kind: Service
metadata:
  name: rulemind-api
spec:
  type: {{ .Values.service.api.type }}
  selector:
    app: rulemind-api
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 8080
